import type { EvJumpstartTheme } from "@/lib/types";

// Avatar: The Last Airbender Jumpstart (set_code: "jtla", cards printed
// under Scryfall code "tle" for JS-main CN 74-170).
//
// 66 variants: 20 common themes × 2 variants + 15 rare themes × 1 +
// 11 mythic themes × 1. Pack distribution is uniform across the 66
// variants — see notes/ev/tla-jumpstart.md for the WOTC+MTGWiki sourced
// tier mapping.
//
// Basic lands (Plains/Island/Swamp/Mountain/Forest and Appa full-art
// basics) are intentionally omitted per j25 convention — they collapse
// under a single card name in the calc's name-lookup and their EV
// contribution is negligible. Thriving lands + Shrines' TLA location
// lands are kept because they have real market value.

export const TLA_JUMPSTART_THEMES: EvJumpstartTheme[] = [
  // ── WHITE ──────────────────────────────────────────────────────────
  {
    name: "Aang",
    variant: 1,
    color: "white",
    tier: "mythic",
    cards: [
      "Aang, Airbending Master",
      "Appa, Loyal Sky Bison",
      "Momo, Rambunctious Rascal",
      "Kindly Customer",
      "Invasion Reinforcements",
      "Water Tribe Captain",
      "Koala-Sheep",
      "Kyoshi Warriors",
      "Cloudshift",
      "Enter the Avatar State",
      "Path to Redemption",
      "Airbending Lesson",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Swordmaster",
    variant: 1,
    color: "white",
    tier: "mythic",
    cards: [
      "Sokka, Swordmaster",
      "Master Piandao",
      "Earth Kingdom Protectors",
      "Kyoshi Battle Fan",
      "Inspired Insurgent",
      "Glider Kids",
      "Aardvark Sloth",
      "Trusty Boomerang",
      "Sokka's Sword Training",
      "Razor Rings",
      "Duelist's Heritage",
      "Meteor Sword",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Airbending",
    variant: 1,
    color: "white",
    tier: "rare",
    cards: [
      "Aang, the Last Airbender",
      "Monk Gyatso",
      "Appa, Loyal Sky Bison",
      "Jeong Jeong's Deserters",
      "Invasion Reinforcements",
      "Glider Kids",
      "Koala-Sheep",
      "Rabaroo Troop",
      "Airbender Ascension",
      "Path to Redemption",
      "Airbending Lesson",
      "Airbender's Reversal",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Freedom Fighters",
    variant: 1,
    color: "white",
    tier: "rare",
    cards: [
      "Jet, Rebel Leader",
      "The Duke, Rebel Sentry",
      "Pipsqueak, Rebel Strongarm",
      "Jeong Jeong's Deserters",
      "Inspired Insurgent",
      "Toucan-Puffin",
      "Wandering Musicians",
      "Rabaroo Troop",
      "Acrobatic Leap",
      "Path to Redemption",
      "Valorous Stance",
      "Hook Swords",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Warriors",
    variant: 1,
    color: "white",
    tier: "rare",
    cards: [
      "Suki, Kyoshi Captain",
      "Sokka, Lateral Strategist",
      "Kyoshi Warrior Guard",
      "Kyoshi Battle Fan",
      "Kyoshi Warriors",
      "Invasion Reinforcements",
      "Toucan-Puffin",
      "Rabaroo Troop",
      "Path to Redemption",
      "Sokka's Sword Training",
      "Valorous Stance",
      "Team Avatar",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Hei Bai",
    variant: 1,
    color: "white",
    tier: "common",
    cards: [
      "Hei Bai, Spirit of Balance",
      "Suki, Courageous Rescuer",
      "Aang, A Lot to Learn",
      "Invasion Reinforcements",
      "Pretending Poxbearers",
      "Koala-Sheep",
      "Vengeful Villagers",
      "Rabaroo Troop",
      "Acrobatic Leap",
      "Path to Redemption",
      "That's Rough Buddy",
      "Sandbenders' Storm",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Hei Bai",
    variant: 2,
    color: "white",
    tier: "common",
    cards: [
      "Hei Bai, Spirit of Balance",
      "Suki, Courageous Rescuer",
      "Aang, A Lot to Learn",
      "Curious Farm Animals",
      "Jeong Jeong's Deserters",
      "Pretending Poxbearers",
      "Aardvark Sloth",
      "Rabaroo Troop",
      "Sokka's Sword Training",
      "Path to Redemption",
      "That's Rough Buddy",
      "Destined Confrontation",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Gliding",
    variant: 1,
    color: "white",
    tier: "common",
    cards: [
      "Momo, Friendly Flier",
      "Aang, the Last Airbender",
      "Appa, Loyal Sky Bison",
      "Air Nomad Student",
      "Kindly Customer",
      "Toucan-Puffin",
      "Koala-Sheep",
      "Rabaroo Troop",
      "Yip Yip!",
      "Path to Redemption",
      "Airbending Lesson",
      "Glider Staff",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Gliding",
    variant: 2,
    color: "white",
    tier: "common",
    cards: [
      "Momo, Friendly Flier",
      "Aang, the Last Airbender",
      "Appa, Loyal Sky Bison",
      "Air Nomad Student",
      "Jeong Jeong's Deserters",
      "Inspired Insurgent",
      "Glider Kids",
      "Water Tribe Captain",
      "Yip Yip!",
      "Path to Redemption",
      "Tale of Momo",
      "Glider Staff",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Insurgent",
    variant: 1,
    color: "white",
    tier: "common",
    cards: [
      "Aang, the Last Airbender",
      "Appa, Loyal Sky Bison",
      "Momo, Rambunctious Rascal",
      "Inspired Insurgent",
      "Jeong Jeong's Deserters",
      "Invasion Reinforcements",
      "Glider Kids",
      "Kyoshi Warriors",
      "Razor Rings",
      "Stand United",
      "Airbender's Reversal",
      "Tale of Momo",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Insurgent",
    variant: 2,
    color: "white",
    tier: "common",
    cards: [
      "Hakoda, Selfless Commander",
      "Sokka, Lateral Strategist",
      "Appa, Loyal Sky Bison",
      "Momo, Rambunctious Rascal",
      "Inspired Insurgent",
      "Kyoshi Warrior Guard",
      "Glider Kids",
      "Kyoshi Warriors",
      "Path to Redemption",
      "Stand United",
      "That's Rough Buddy",
      "Duelist's Heritage",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Alliance",
    variant: 1,
    color: "white",
    tier: "common",
    cards: [
      "Jet, Freedom Fighter",
      "Suki, Kyoshi Warrior",
      "Sokka, Lateral Strategist",
      "The Duke, Rebel Sentry",
      "South Pole Voyager",
      "Kyoshi Warrior Guard",
      "Glider Kids",
      "Kyoshi Warriors",
      "Mechanical Glider",
      "Sokka's Sword Training",
      "Path to Redemption",
      "Fancy Footwork",
      "Thriving Heath",
      "Plains",
    ],
  },
  {
    name: "Alliance",
    variant: 2,
    color: "white",
    tier: "common",
    cards: [
      "Jet, Rebel Leader",
      "Suki, Kyoshi Warrior",
      "Sokka, Lateral Strategist",
      "The Duke, Rebel Sentry",
      "South Pole Voyager",
      "Inspired Insurgent",
      "Glider Kids",
      "Kyoshi Warriors",
      "Mechanical Glider",
      "Acrobatic Leap",
      "Razor Rings",
      "Fancy Footwork",
      "Thriving Heath",
      "Plains",
    ],
  },

  // ── BLUE ───────────────────────────────────────────────────────────
  {
    name: "Katara",
    variant: 1,
    color: "blue",
    tier: "mythic",
    cards: [
      "Katara, Waterbending Master",
      "Master Pakku",
      "Gran-Gran",
      "Sokka, Lateral Strategist",
      "Rowdy Snowballers",
      "Turtle-Seals",
      "Geyser Leaper",
      "Consider",
      "Watery Grasp",
      "Octopus Form",
      "It'll Quench Ya!",
      "Sokka's Haiku",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Librarian",
    variant: 1,
    color: "blue",
    tier: "mythic",
    cards: [
      "Wan Shi Tong, All-Knowing",
      "Professor Zei, Anthropologist",
      "Suspicious Bookcase",
      "Knowledge Seeker",
      "Dutiful Knowledge Seeker",
      "Giant Koi",
      "Brainstorm",
      "Octopus Form",
      "Accumulate Wisdom",
      "Lost in the Spirit World",
      "Waterbending Lesson",
      "Zuko's Exile",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Adaptive",
    variant: 1,
    color: "blue",
    tier: "rare",
    cards: [
      "The Blue Spirit",
      "Katara, Bending Prodigy",
      "Princess Yue",
      "Teo, Spirited Glider",
      "Glider Kids",
      "Kyoshi Battle Fan",
      "Rowdy Snowballers",
      "Giant Koi",
      "Boomerang Basics",
      "Frantic Search",
      "Lost in the Spirit World",
      "Waterbending Lesson",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Spirit",
    variant: 1,
    color: "blue",
    tier: "rare",
    cards: [
      "Baboon Spirit",
      "Benevolent River Spirit",
      "Flying Dolphin-Fish",
      "Knowledge Seeker",
      "Dutiful Knowledge Seeker",
      "Flexible Waterbender",
      "Giant Koi",
      "Octopus Form",
      "Dramatic Reversal",
      "It'll Quench Ya!",
      "Lost in the Spirit World",
      "The Spirit Oasis",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Underwater",
    variant: 1,
    color: "blue",
    tier: "rare",
    cards: [
      "Tui and La, Moon and Ocean",
      "Flying Dolphin-Fish",
      "Invasion Submersible",
      "Rowdy Snowballers",
      "Turtle-Seals",
      "Giant Koi",
      "Serpent of the Pass",
      "Unagi's Spray",
      "Octopus Form",
      "Honest Work",
      "Coastal Piracy",
      "White Lotus Hideout",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Wise",
    variant: 1,
    color: "blue",
    tier: "common",
    cards: [
      "Gran-Gran",
      "Katara, Bending Prodigy",
      "Forecasting Fortune Teller",
      "Otter-Penguin",
      "Rowdy Snowballers",
      "Messenger Hawk",
      "Turtle-Seals",
      "Consider",
      "Waterbender's Restoration",
      "Waterbending Lesson",
      "Coastal Piracy",
      "Whirlwind Technique",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Wise",
    variant: 2,
    color: "blue",
    tier: "common",
    cards: [
      "The Blue Spirit",
      "Sokka, Lateral Strategist",
      "Knowledge Seeker",
      "Tiger-Seal",
      "Otter-Penguin",
      "Rowdy Snowballers",
      "Messenger Hawk",
      "Turtle-Seals",
      "Consider",
      "It'll Quench Ya!",
      "Sokka's Haiku",
      "Whirlwind Technique",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Soaring",
    variant: 1,
    color: "blue",
    tier: "common",
    cards: [
      "The Mechanist, Aerial Artisan",
      "Sokka, Lateral Strategist",
      "Teo, Spirited Glider",
      "Flying Dolphin-Fish",
      "Forecasting Fortune Teller",
      "Messenger Hawk",
      "Cat-Owl",
      "Giant Koi",
      "Watery Grasp",
      "Mechanical Glider",
      "Boomerang Basics",
      "Sokka's Haiku",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Soaring",
    variant: 2,
    color: "blue",
    tier: "common",
    cards: [
      "Yue, the Moon Spirit",
      "Sokka, Lateral Strategist",
      "Teo, Spirited Glider",
      "Flying Dolphin-Fish",
      "Benevolent River Spirit",
      "Messenger Hawk",
      "Cat-Owl",
      "Giant Koi",
      "Watery Grasp",
      "Octopus Form",
      "Boomerang Basics",
      "Frantic Search",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Adept",
    variant: 1,
    color: "blue",
    tier: "common",
    cards: [
      "Katara, Bending Prodigy",
      "Professor Zei, Anthropologist",
      "Forecasting Fortune Teller",
      "Iguana Parrot",
      "Turtle-Seals",
      "Giant Koi",
      "Serpent of the Pass",
      "Unagi's Spray",
      "Dramatic Reversal",
      "Crashing Wave",
      "Nightmares and Daydreams",
      "Waterbending Lesson",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Adept",
    variant: 2,
    color: "blue",
    tier: "common",
    cards: [
      "Katara, Bending Prodigy",
      "Professor Zei, Anthropologist",
      "Master Pakku",
      "Teo, Spirited Glider",
      "Iguana Parrot",
      "Geyser Leaper",
      "Serpent of the Pass",
      "Octopus Form",
      "Consider",
      "Nightmares and Daydreams",
      "Waterbending Lesson",
      "Lost Days",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Lessons",
    variant: 1,
    color: "blue",
    tier: "common",
    cards: [
      "Katara, Seeking Revenge",
      "Gran-Gran",
      "Glider Kids",
      "Platypus-Bear",
      "Iguana Parrot",
      "Giant Koi",
      "Octopus Form",
      "Boomerang Basics",
      "Accumulate Wisdom",
      "It'll Quench Ya!",
      "Chakra Meditation",
      "Whirlwind Technique",
      "Thriving Isle",
      "Island",
    ],
  },
  {
    name: "Lessons",
    variant: 2,
    color: "blue",
    tier: "common",
    cards: [
      "Katara, Seeking Revenge",
      "Gran-Gran",
      "Master Pakku",
      "Platypus-Bear",
      "Iguana Parrot",
      "Geyser Leaper",
      "Octopus Form",
      "Accumulate Wisdom",
      "Chakra Meditation",
      "Waterbending Lesson",
      "Lost Days",
      "Whirlwind Technique",
      "Thriving Isle",
      "Island",
    ],
  },

  // ── BLACK ──────────────────────────────────────────────────────────
  {
    name: "Azula",
    variant: 1,
    color: "black",
    tier: "mythic",
    cards: [
      "Azula, Ruthless Firebender",
      "Lo and Li, Twin Tutors",
      "Dai Li Censor",
      "Corrupt Court Official",
      "Fire Nation Ambushers",
      "Fire Navy Trebuchet",
      "Canyon Crawler",
      "Sold Out",
      "Azula Always Lies",
      "Dai Li Indoctrination",
      "Epic Downfall",
      "Dark Deal",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Ozai",
    variant: 1,
    color: "black",
    tier: "mythic",
    cards: [
      "Fire Lord Ozai",
      "Zhao, Ruthless Admiral",
      "Callous Inspector",
      "Corrupt Court Official",
      "Fire Nation Ambushers",
      "Fire Navy Trebuchet",
      "Beetle-Headed Merchants",
      "Canyon Crawler",
      "Heartless Act",
      "Ozai's Cruelty",
      "Scarring Memories",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Bad Advice",
    variant: 1,
    color: "black",
    tier: "rare",
    cards: [
      "Lo and Li, Royal Advisors",
      "Long Feng, Grand Secretariat",
      "Hama, the Bloodbender",
      "Joo Dee, One of Many",
      "Gilacorn",
      "Dai Li Censor",
      "Corrupt Court Official",
      "Fire Nation Ambushers",
      "Sold Out",
      "Dai Li Indoctrination",
      "Ozai's Cruelty",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Nightmares",
    variant: 1,
    color: "black",
    tier: "rare",
    cards: [
      "Koh, the Face Stealer",
      "Azula, On the Hunt",
      "Hei Bai, Spirit of Balance",
      "Joo Dee, One of Many",
      "Purple Pentapus",
      "Pretending Poxbearers",
      "Pirate Peddlers",
      "Canyon Crawler",
      "Zuko's Conviction",
      "Desperate Plea",
      "Ruinous Waterbending",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Siege Engines",
    variant: 1,
    color: "black",
    tier: "rare",
    cards: [
      "The Fire Nation Drill",
      "Callous Inspector",
      "Merchant of Many Hats",
      "Pretending Poxbearers",
      "Fire Nation Engineer",
      "Fire Navy Trebuchet",
      "Fire Nation Warship",
      "Tundra Tank",
      "Beetle-Headed Merchants",
      "Canyon Crawler",
      "Heartless Act",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Bounty Hunter",
    variant: 1,
    color: "black",
    tier: "common",
    cards: [
      "June, Bounty Hunter",
      "Nyla, Shirshu Sleuth",
      "Azula, On the Hunt",
      "Purple Pentapus",
      "Pretending Poxbearers",
      "Pirate Peddlers",
      "Giant Fly",
      "Beetle-Headed Merchants",
      "Sold Out",
      "Zuko's Conviction",
      "Bastion of Remembrance",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Bounty Hunter",
    variant: 2,
    color: "black",
    tier: "common",
    cards: [
      "June, Bounty Hunter",
      "Nyla, Shirshu Sleuth",
      "Azula, On the Hunt",
      "Zhao, Ruthless Admiral",
      "Callous Inspector",
      "Pretending Poxbearers",
      "Pirate Peddlers",
      "Fire Navy Trebuchet",
      "Sold Out",
      "Obsessive Pursuit",
      "Bastion of Remembrance",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Relentless",
    variant: 1,
    color: "black",
    tier: "common",
    cards: [
      "Azula, On the Hunt",
      "Purple Pentapus",
      "Merchant of Many Hats",
      "Ruthless Waterbender",
      "Pirate Peddlers",
      "Fire Nation Ambushers",
      "Buzzard-Wasp Colony",
      "Canyon Crawler",
      "Sold Out",
      "Azula Always Lies",
      "Heartless Act",
      "Fire Nation Occupation",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Relentless",
    variant: 2,
    color: "black",
    tier: "common",
    cards: [
      "Azula, On the Hunt",
      "Zhao, Ruthless Admiral",
      "Callous Inspector",
      "Merchant of Many Hats",
      "Joo Dee, One of Many",
      "Fire Nation Ambushers",
      "Beetle-Headed Merchants",
      "Canyon Crawler",
      "Azula Always Lies",
      "Heartless Act",
      "Fire Nation Occupation",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Reinforced",
    variant: 1,
    color: "black",
    tier: "common",
    cards: [
      "Zuko, Seeking Honor",
      "Long Feng, Grand Secretariat",
      "Callous Inspector",
      "Elephant-Rat",
      "Hog-Monkey",
      "Buzzard-Wasp Colony",
      "Fire Nation Salvagers",
      "Beetle-Headed Merchants",
      "Azula Always Lies",
      "Dai Li Indoctrination",
      "Epic Downfall",
      "Feed the Swarm",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Reinforced",
    variant: 2,
    color: "black",
    tier: "common",
    cards: [
      "Zuko, Seeking Honor",
      "Long Feng, Grand Secretariat",
      "Gilacorn",
      "Elephant-Rat",
      "Hog-Monkey",
      "Earth Village Ruffians",
      "Buzzard-Wasp Colony",
      "Fire Nation Salvagers",
      "Fatal Fissure",
      "Dai Li Indoctrination",
      "Heartless Act",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Hunting",
    variant: 1,
    color: "black",
    tier: "common",
    cards: [
      "June, Bounty Hunter",
      "Katara, Seeking Revenge",
      "Purple Pentapus",
      "Elephant-Rat",
      "Raven Eagle",
      "Messenger Hawk",
      "Foggy Swamp Hunters",
      "Beetle-Headed Merchants",
      "Desperate Plea",
      "Epic Downfall",
      "Diresight",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },
  {
    name: "Hunting",
    variant: 2,
    color: "black",
    tier: "common",
    cards: [
      "June, Bounty Hunter",
      "Katara, Seeking Revenge",
      "Gilacorn",
      "Ruthless Waterbender",
      "Raven Eagle",
      "Messenger Hawk",
      "Foggy Swamp Hunters",
      "Beetle-Headed Merchants",
      "Azula Always Lies",
      "Swampsnare Trap",
      "Diresight",
      "Deadly Precision",
      "Thriving Moor",
      "Swamp",
    ],
  },

  // ── RED ────────────────────────────────────────────────────────────
  {
    name: "Roku",
    variant: 1,
    color: "red",
    tier: "mythic",
    cards: [
      "Avatar Roku, Firebender",
      "Fang, Roku's Companion",
      "Jeong Jeong, the Deserter",
      "Loyal Fire Sage",
      "Fire Sages",
      "Yuyan Archers",
      "Boar-q-pine",
      "Firebending Lesson",
      "Frantic Confrontation",
      "Roku's Mastery",
      "Crescent Island Temple",
      "White Lotus Hideout",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Zuko",
    variant: 1,
    color: "red",
    tier: "mythic",
    cards: [
      "Zuko, Firebending Master",
      "Mai, Jaded Edge",
      "Yuyan Archers",
      "War Balloon",
      "Dragon Moose",
      "Mongoose Lizard",
      "Fire Nation Attacks",
      "Firebending Lesson",
      "Frantic Confrontation",
      "Fists of Flame",
      "Lightning Strike",
      "Lost in Memories",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Fire Nation",
    variant: 1,
    color: "red",
    tier: "rare",
    cards: [
      "Firebending Student",
      "Mai, Jaded Edge",
      "Ty Lee, Artful Acrobat",
      "Zuko, Seeking Honor",
      "Longshot, Rebel Bowman",
      "Fire Nation Attacks",
      "Firebending Lesson",
      "Cunning Maneuver",
      "Fists of Flame",
      "Lightning Strike",
      "How to Start a Riot",
      "Storm of Memories",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Iroh",
    variant: 1,
    color: "red",
    tier: "rare",
    cards: [
      "Iroh, Dragon of the West",
      "Jeong Jeong, the Deserter",
      "Deserter's Disciple",
      "Tiger-Dillo",
      "Boar-q-pine",
      "Zuko, Seeking Honor",
      "Mongoose Lizard",
      "Firebending Lesson",
      "Iroh's Demonstration",
      "Cathartic Reunion",
      "Bolt Bend",
      "Fiery Confluence",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Musicians",
    variant: 1,
    color: "red",
    tier: "rare",
    cards: [
      "Chong and Lily, Nomads",
      "Moku, Meandering Drummer",
      "Ty Lee, Artful Acrobat",
      "Freedom Fighter Recruit",
      "Founding of Omashu",
      "Wandering Musicians",
      "Rough Rhino Cavalry",
      "Mongoose Lizard",
      "Explosive Shot",
      "Cunning Maneuver",
      "Bumi Bash",
      "The Cave of Two Lovers",
      "Secret Tunnel",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Firebending",
    variant: 1,
    color: "red",
    tier: "common",
    cards: [
      "Jeong Jeong, the Deserter",
      "Zuko, Exiled Prince",
      "Fire Nation Cadets",
      "Fire Sages",
      "Loyal Fire Sage",
      "Dragon Moose",
      "Firebender Ascension",
      "Firebending Lesson",
      "Roku's Mastery",
      "Cunning Maneuver",
      "Lightning Strike",
      "Reckless Blaze",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Firebending",
    variant: 2,
    color: "red",
    tier: "common",
    cards: [
      "Jeong Jeong, the Deserter",
      "Zuko, Exiled Prince",
      "Moku, Meandering Drummer",
      "Fire Nation Cadets",
      "Yuyan Archers",
      "Loyal Fire Sage",
      "Rough Rhino Cavalry",
      "Fire Nation Attacks",
      "Firebending Lesson",
      "Cunning Maneuver",
      "Combustion Technique",
      "Reckless Blaze",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Powerful",
    variant: 1,
    color: "red",
    tier: "common",
    cards: [
      "Fang, Roku's Companion",
      "Uncle Iroh",
      "Deserter's Disciple",
      "Tiger-Dillo",
      "Earth Rumble Wrestlers",
      "Fire Nation Raider",
      "Rough Rhino Cavalry",
      "Mongoose Lizard",
      "Firebending Lesson",
      "Iroh's Demonstration",
      "Cathartic Reunion",
      "Twin Blades",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Powerful",
    variant: 2,
    color: "red",
    tier: "common",
    cards: [
      "Fang, Roku's Companion",
      "Uncle Iroh",
      "Combustion Man",
      "Freedom Fighter Recruit",
      "Tiger-Dillo",
      "Komodo Rhino",
      "Fire Nation Raider",
      "Mongoose Lizard",
      "Firebending Lesson",
      "Hog-Monkey Rampage",
      "Cathartic Reunion",
      "How to Start a Riot",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Rebelling",
    variant: 1,
    color: "red",
    tier: "common",
    cards: [
      "Jet, Freedom Fighter",
      "Smellerbee, Rebel Fighter",
      "Zuko, Seeking Honor",
      "Freedom Fighter Recruit",
      "Yuyan Archers",
      "Treetop Freedom Fighters",
      "Longshot, Rebel Bowman",
      "Fire Nation Attacks",
      "Explosive Shot",
      "Cunning Maneuver",
      "How to Start a Riot",
      "Bumi Bash",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Rebelling",
    variant: 2,
    color: "red",
    tier: "common",
    cards: [
      "Jet, Freedom Fighter",
      "Smellerbee, Rebel Fighter",
      "Zuko, Seeking Honor",
      "Freedom Fighter Recruit",
      "Deserter's Disciple",
      "Treetop Freedom Fighters",
      "Longshot, Rebel Bowman",
      "Hook Swords",
      "Explosive Shot",
      "Run Amok",
      "How to Start a Riot",
      "Overwhelming Victory",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Sparky Sparky",
    variant: 1,
    color: "red",
    tier: "common",
    cards: [
      "Combustion Man",
      "Ran and Shaw",
      "Zuko, Exiled Prince",
      "Fire Nation Cadets",
      "Fire Sages",
      "Deer-Dog",
      "War Balloon",
      "Earth Rumble Wrestlers",
      "Iroh's Demonstration",
      "Combustion Technique",
      "How to Start a Riot",
      "Bumi Bash",
      "Thriving Bluff",
      "Mountain",
    ],
  },
  {
    name: "Sparky Sparky",
    variant: 2,
    color: "red",
    tier: "common",
    cards: [
      "Combustion Man",
      "Ran and Shaw",
      "Zuko, Exiled Prince",
      "Fire Nation Cadets",
      "Yuyan Archers",
      "Deer-Dog",
      "War Balloon",
      "Dragon Moose",
      "Firebending Lesson",
      "Combustion Technique",
      "Price of Freedom",
      "Overwhelming Victory",
      "Thriving Bluff",
      "Mountain",
    ],
  },

  // ── GREEN ──────────────────────────────────────────────────────────
  {
    name: "Kyoshi",
    variant: 1,
    color: "green",
    tier: "mythic",
    cards: [
      "Avatar Kyoshi, Earthbender",
      "Suki, Kyoshi Warrior",
      "Kyoshi Warrior Exemplars",
      "Kyoshi Battle Fan",
      "Raucous Audience",
      "Elephant-Mandrill",
      "Earth Kingdom Soldier",
      "Rocky Rebuke",
      "Cycle of Renewal",
      "Allies at Last",
      "Cracked Earth Technique",
      "Tectonic Split",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Toph",
    variant: 1,
    color: "green",
    tier: "mythic",
    cards: [
      "Toph, Earthbending Master",
      "Earth Kingdom General",
      "Rebellious Captives",
      "Frog-Squirrels",
      "Earth Kingdom Soldier",
      "Kyoshi Warrior Exemplars",
      "Badgermole",
      "Saber-Tooth Moose-Lion",
      "Rocky Rebuke",
      "Origin of Metalbending",
      "Tale of Katara and Toph",
      "Solid Ground",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "At the Zoo",
    variant: 1,
    color: "green",
    tier: "rare",
    cards: [
      "Diligent Zookeeper",
      "Turtle-Duck",
      "Animal Attendant",
      "Frog-Squirrels",
      "Ostrich-Horse",
      "Elephant-Mandrill",
      "Eel-Hounds",
      "Saber-Tooth Moose-Lion",
      "Pillar Launch",
      "Origin of Metalbending",
      "Bison Whistle",
      "Hog-Monkey Rampage",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Bumi",
    variant: 1,
    color: "green",
    tier: "rare",
    cards: [
      "Bumi, King of Three Trials",
      "Flopsie, Bumi's Buddy",
      "Aang, A Lot to Learn",
      "Raucous Audience",
      "Bumi's Feast Lecture",
      "Walltop Sentries",
      "Earthbending Lesson",
      "Badgermole",
      "Origin of Metalbending",
      "Rocky Rebuke",
      "Creeping Crystal Coating",
      "Crystalline Armor",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Cabbages",
    variant: 1,
    color: "green",
    tier: "rare",
    cards: [
      "The Cabbage Merchant",
      "Bosco, Just a Bear",
      "Unlucky Cabbage Merchant",
      "Bumi's Feast Lecture",
      "Elephant-Mandrill",
      "Foggy Swamp Vinebender",
      "Hippo-Cows",
      "Saber-Tooth Moose-Lion",
      "Many Partings",
      "Leaves from the Vine",
      "The Art of Tea",
      "Rocky Rebuke",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Earth Kingdom",
    variant: 1,
    color: "green",
    tier: "common",
    cards: [
      "Haru, Hidden Talent",
      "Toph, the Blind Bandit",
      "Suki, Kyoshi Warrior",
      "Kyoshi Battle Fan",
      "Match the Odds",
      "Foggy Swamp Vinebender",
      "Earth Kingdom Soldier",
      "Hippo-Cows",
      "Mechanical Glider",
      "Stand United",
      "Descendants' Path",
      "Allies at Last",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Earth Kingdom",
    variant: 2,
    color: "green",
    tier: "common",
    cards: [
      "Haru, Hidden Talent",
      "Toph, the Blind Bandit",
      "Suki, Kyoshi Warrior",
      "Great Divide Guide",
      "Earth Kingdom General",
      "Walltop Sentries",
      "Earth Kingdom Soldier",
      "Hippo-Cows",
      "Mechanical Glider",
      "Origin of Metalbending",
      "Descendants' Path",
      "Allies at Last",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Earth Rumble",
    variant: 1,
    color: "green",
    tier: "common",
    cards: [
      "The Boulder, Ready to Rumble",
      "Toph, the Blind Bandit",
      "Uncle Iroh",
      "Rebellious Captives",
      "Raucous Audience",
      "Kyoshi Battle Fan",
      "Earth Rumble Wrestlers",
      "Hippo-Cows",
      "Pillar Launch",
      "Hog-Monkey Rampage",
      "Master's Guidance",
      "Earth Rumble",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Earth Rumble",
    variant: 2,
    color: "green",
    tier: "common",
    cards: [
      "The Boulder, Ready to Rumble",
      "The Earth King",
      "Uncle Iroh",
      "Frog-Squirrels",
      "Raucous Audience",
      "Kyoshi Battle Fan",
      "Earth Rumble Wrestlers",
      "Bosco, Just a Bear",
      "Origin of Metalbending",
      "Hog-Monkey Rampage",
      "Allies at Last",
      "Master's Guidance",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Earthbending",
    variant: 1,
    color: "green",
    tier: "common",
    cards: [
      "Toph, the Blind Bandit",
      "Earth Kingdom General",
      "Turtle-Duck",
      "Rebellious Captives",
      "Earth Kingdom Soldier",
      "Hippo-Cows",
      "Earthbending Lesson",
      "Explore",
      "Rocky Rebuke",
      "Earthbender Ascension",
      "Inspiring Call",
      "Rumble Arena",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Earthbending",
    variant: 2,
    color: "green",
    tier: "common",
    cards: [
      "Toph, the Blind Bandit",
      "Earth Kingdom General",
      "Rebellious Captives",
      "Frog-Squirrels",
      "Earth Kingdom Soldier",
      "Badgermole",
      "Earthbending Lesson",
      "Explore",
      "Rocky Rebuke",
      "Tale of Katara and Toph",
      "Solid Ground",
      "Rumble Arena",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Learning",
    variant: 1,
    color: "green",
    tier: "common",
    cards: [
      "Aang, A Lot to Learn",
      "Guru Pathik",
      "Rebellious Captives",
      "Sparring Dummy",
      "Walltop Sentries",
      "Saber-Tooth Moose-Lion",
      "Origin of Metalbending",
      "Shared Roots",
      "Rocky Rebuke",
      "Crystalline Armor",
      "Cracked Earth Technique",
      "Zuko's Exile",
      "Thriving Grove",
      "Forest",
    ],
  },
  {
    name: "Learning",
    variant: 2,
    color: "green",
    tier: "common",
    cards: [
      "Aang, A Lot to Learn",
      "Uncle Iroh",
      "Platypus-Bear",
      "Sparring Dummy",
      "Walltop Sentries",
      "Saber-Tooth Moose-Lion",
      "The Art of Tea",
      "True Ancestry",
      "Rocky Rebuke",
      "Master's Guidance",
      "Cracked Earth Technique",
      "Zuko's Exile",
      "Thriving Grove",
      "Forest",
    ],
  },

  // ── MULTICOLOR ─────────────────────────────────────────────────────
  {
    name: "Shrines",
    variant: 1,
    color: "multi",
    tier: "mythic",
    cards: [
      "Hei Bai, Forest Guardian",
      "Guru Pathik",
      "Raucous Audience",
      "Walltop Sentries",
      "Saber-Tooth Moose-Lion",
      "Barrels of Blasting Jelly",
      "Northern Air Temple",
      "Aang's Journey",
      "The Spirit Oasis",
      "Kyoshi Island Plaza",
      "Southern Air Temple",
      "Crescent Island Temple",
      "White Lotus Hideout",
      "Thriving Grove",
      "Forest",
    ],
  },
];
