// lib/ev-mb2-list.ts
//
// Mystery Booster 2 pick-up reprint card list (1451 cards).
// These cards are in the "plst" (The List) set on Scryfall.
// original_set is the set code shown on the physical card (for reference only).

export const MB2_PICKUP_CARDS: { name: string; original_set: string }[] = [
  // ── White (258) ────────────────────────────────────
  { name: "Abolish", original_set: "PCY" },
  { name: "Abzan Battle Priest", original_set: "KTK" },
  { name: "Accorder Paladin", original_set: "MBS" },
  { name: "Adamant Will", original_set: "DAR" },
  { name: "Aerial Responder", original_set: "E01" },
  { name: "Afterlife", original_set: "MIR" },
  { name: "Against All Odds", original_set: "ONE" },
  { name: "Ajani's Welcome", original_set: "M19" },
  { name: "Akroan Phalanx", original_set: "BNG" },
  { name: "Akroma, Angel of Wrath", original_set: "DD3" },
  { name: "Alharu, Solemn Ritualist", original_set: "CMR" },
  { name: "All That Glitters", original_set: "ELD" },
  { name: "Alseid of Life's Bounty", original_set: "THB" },
  { name: "Ancestor Dragon", original_set: "GS1" },
  { name: "Ancestral Blade", original_set: "2XM" },
  { name: "Angel of Light", original_set: "ME2" },
  { name: "Angel of Vitality", original_set: "M20" },
  { name: "Angelic Blessing", original_set: "POR" },
  { name: "Angelic Exaltation", original_set: "RNA" },
  { name: "Angelic Favor", original_set: "NEM" },
  { name: "Angelic Page", original_set: "USG" },
  { name: "Angelic Protector", original_set: "TMP" },
  { name: "Archivist of Oghma", original_set: "CLB" },
  { name: "Archon of Absolution", original_set: "ELD" },
  { name: "Armored Ascension", original_set: "SHM" },
  { name: "Authority of the Consuls", original_set: "KLD" },
  { name: "Aven Liberator", original_set: "SCG" },
  { name: "Aven Mindcensor", original_set: "TSR" },
  { name: "Aven Squire", original_set: "CON" },
  { name: "Avian Changeling", original_set: "LRW" },
  { name: "Azorius Herald", original_set: "GK2" },
  { name: "Baffling End", original_set: "RIX" },
  { name: "Baird, Steward of Argive", original_set: "DAR" },
  { name: "Balance", original_set: "EMA" },
  { name: "Banisher Priest", original_set: "M14" },
  { name: "Banishing Light", original_set: "JOU" },
  { name: "Banishing Slash", original_set: "NEO" },
  { name: "Banishing Stroke", original_set: "AVR" },
  { name: "Barbed Spike", original_set: "MH2" },
  { name: "Basri's Acolyte", original_set: "M21" },
  { name: "Basri's Solidarity", original_set: "M21" },
  { name: "Battle Screech", original_set: "JUD" },
  { name: "Belfry Spirit", original_set: "GK2" },
  { name: "Bellowing Aegisaur", original_set: "XLN" },
  { name: "Beloved Chaplain", original_set: "ODY" },
  { name: "Benevolent Bodyguard", original_set: "JUD" },
  { name: "Bishop of Wings", original_set: "M20" },
  { name: "Blessed Defiance", original_set: "J22" },
  { name: "Bond of Discipline", original_set: "WAR" },
  { name: "Boonweaver Giant", original_set: "M15" },
  { name: "Boros Elite", original_set: "GK1" },
  { name: "Breath of Life", original_set: "POR" },
  { name: "Brightling", original_set: "BBD" },
  { name: "Burrenton Forge-Tender", original_set: "LRW" },
  { name: "Cataclysm", original_set: "V14" },
  { name: "Cenn's Enlistment", original_set: "EVE" },
  { name: "Charming Prince", original_set: "ELD" },
  { name: "Chastise", original_set: "JUD" },
  { name: "Clarion Spirit", original_set: "KHM" },
  { name: "Cleric Class", original_set: "AFR" },
  { name: "Cloudgoat Ranger", original_set: "LRW" },
  { name: "Condemn", original_set: "DIS" },
  { name: "Constricting Sliver", original_set: "M15" },
  { name: "Consul's Lieutenant", original_set: "ORI" },
  { name: "Contraband Livestock", original_set: "CLB" },
  { name: "Crossbow Infantry", original_set: "MMQ" },
  { name: "Custodi Squire", original_set: "CNS" },
  { name: "Daru Spiritualist", original_set: "SCG" },
  { name: "Dauntless Bodyguard", original_set: "DAR" },
  { name: "Dawnbringer Cleric", original_set: "AFR" },
  { name: "Daxos, Blessed by the Sun", original_set: "THB" },
  { name: "Deftblade Elite", original_set: "LGN" },
  { name: "Desperate Lunge", original_set: "WAR" },
  { name: "Destroy Evil", original_set: "DMU" },
  { name: "Devout Witness", original_set: "MMQ" },
  { name: "Diversionary Tactics", original_set: "APC" },
  { name: "Elite Scaleguard", original_set: "CM2" },
  { name: "Elspeth's Smite", original_set: "MOM" },
  { name: "Empty-Shrine Kannushi", original_set: "BOK" },
  { name: "Ethereal Armor", original_set: "Q06" },
  { name: "Evangel of Heliod", original_set: "THS" },
  { name: "Exile", original_set: "VMA" },
  { name: "Faerie Guidemother", original_set: "ELD" },
  { name: "Fairgrounds Warden", original_set: "KLD" },
  { name: "Faith Unbroken", original_set: "EMN" },
  { name: "Fanatical Devotion", original_set: "NEM" },
  { name: "Fearless Fledgling", original_set: "ZNR" },
  { name: "Field of Souls", original_set: "VOW" },
  { name: "Fierce Retribution", original_set: "VOW" },
  { name: "Flickerwisp", original_set: "EVE" },
  { name: "Generous Gift", original_set: "MH1" },
  { name: "Genju of the Fields", original_set: "BOK" },
  { name: "Ghostly Prison", original_set: "CHK" },
  { name: "Gideon, Ally of Zendikar", original_set: "BFZ" },
  { name: "Glimmerpoint Stag", original_set: "SOM" },
  { name: "Goldmeadow Harrier", original_set: "DDF" },
  { name: "Goldnight Commander", original_set: "AVR" },
  { name: "Grateful Apparition", original_set: "WAR" },
  { name: "Griffin Guide", original_set: "TSR" },
  { name: "Hand of Honor", original_set: "SOK" },
  { name: "Healer of the Pride", original_set: "M13" },
  { name: "Heliod's Punishment", original_set: "THB" },
  { name: "Hive Stirrings", original_set: "M14" },
  { name: "Hope and Glory", original_set: "ULG" },
  { name: "Hushbringer", original_set: "ELD" },
  { name: "Imperial Oath", original_set: "NEO" },
  { name: "Imposing Vantasaur", original_set: "IKO" },
  { name: "Impostor of the Sixth Pride", original_set: "MH1" },
  { name: "Inspiring Overseer", original_set: "SNC" },
  { name: "Intangible Virtue", original_set: "ISD" },
  { name: "Irregular Cohort", original_set: "MH1" },
  { name: "Jötun Owl Keeper", original_set: "CSP" },
  { name: "Journey to Nowhere", original_set: "ZEN" },
  { name: "Kabira Vindicator", original_set: "DDP" },
  { name: "Kami of False Hope", original_set: "BOK" },
  { name: "Karametra's Blessing", original_set: "THB" },
  { name: "Karoo", original_set: "VIS" },
  { name: "Kitsune Blademaster", original_set: "CHK" },
  { name: "Knight of Meadowgrain", original_set: "DDG" },
  { name: "Knight of the Holy Nimbus", original_set: "TSP" },
  { name: "Knightly Valor", original_set: "RTR" },
  { name: "Kor Cartographer", original_set: "DDI" },
  { name: "Kor Celebrant", original_set: "ZNR" },
  { name: "Lagonna-Band Trailblazer", original_set: "JOU" },
  { name: "Last Breath", original_set: "MMQ" },
  { name: "Loam Lion", original_set: "WWK" },
  { name: "Make a Stand", original_set: "OGW" },
  { name: "Master Decoy", original_set: "TMP" },
  { name: "Master of Arms", original_set: "WTH" },
  { name: "Master Splicer", original_set: "NPH" },
  { name: "Mentor of the Meek", original_set: "2X2" },
  { name: "Militia Bugler", original_set: "2X2" },
  { name: "Ministrant of Obligation", original_set: "RNA" },
  { name: "Miraculous Recovery", original_set: "VIS" },
  { name: "Mistmeadow Skulk", original_set: "SHM" },
  { name: "Mistveil Plains", original_set: "UMA" },
  { name: "Moment of Triumph", original_set: "RIX" },
  { name: "Moon-Blessed Cleric", original_set: "AFR" },
  { name: "Mother of Runes", original_set: "ULG" },
  { name: "Myth Realized", original_set: "2X2" },
  { name: "Nearheath Pilgrim", original_set: "AVR" },
  { name: "Nightwind Glider", original_set: "MMQ" },
  { name: "Nikko-Onna", original_set: "SOK" },
  { name: "Noble Purpose", original_set: "MMQ" },
  { name: "Oathsworn Giant", original_set: "RAV" },
  { name: "Oblivion Ring", original_set: "LRW" },
  { name: "Omen of the Sun", original_set: "THB" },
  { name: "On Serra's Wings", original_set: "DAR" },
  { name: "Orzhov Advokist", original_set: "C16" },
  { name: "Ossification", original_set: "ONE" },
  { name: "Otherworldly Journey", original_set: "DDC" },
  { name: "Pegasus Guardian", original_set: "CLB" },
  { name: "Perimeter Captain", original_set: "WWK" },
  { name: "Phantom Flock", original_set: "JUD" },
  { name: "Phyrexian Missionary", original_set: "DMU" },
  { name: "Planar Disruption", original_set: "ONE" },
  { name: "Plate Armor", original_set: "AFR" },
  { name: "Porcelain Legionnaire", original_set: "NPH" },
  { name: "Portable Hole", original_set: "AFR" },
  { name: "Prava of the Steel Legion", original_set: "ONE" },
  { name: "Prismatic Strands", original_set: "JUD" },
  { name: "Prison Term", original_set: "SHM" },
  { name: "Radiant's Judgment", original_set: "ULG" },
  { name: "Raffine's Informant", original_set: "SNC" },
  { name: "Raise the Alarm", original_set: "MD1" },
  { name: "Rambunctious Mutt", original_set: "M21" },
  { name: "Ramosian Rally", original_set: "MMQ" },
  { name: "Ranger of Eos", original_set: "MM3" },
  { name: "Rebuff the Wicked", original_set: "PLC" },
  { name: "Reconnaissance", original_set: "EXO" },
  { name: "Recumbent Bliss", original_set: "EVE" },
  { name: "Refuse to Yield", original_set: "SNC" },
  { name: "Release the Dogs", original_set: "M21" },
  { name: "Resolute Reinforcements", original_set: "DMU" },
  { name: "Restoration Specialist", original_set: "AER" },
  { name: "Reveille Squad", original_set: "PCY" },
  { name: "Reverent Hoplite", original_set: "THB" },
  { name: "Rhox Meditant", original_set: "CON" },
  { name: "Rumor Gatherer", original_set: "SNC" },
  { name: "Sage's Reverie", original_set: "C18" },
  { name: "Samurai of the Pale Curtain", original_set: "CHK" },
  { name: "Sentinel Sliver", original_set: "M14" },
  { name: "Seraph of Dawn", original_set: "AVR" },
  { name: "Settle Beyond Reality", original_set: "MH1" },
  { name: "Settle the Wreckage", original_set: "XLN" },
  { name: "Shattered Angel", original_set: "NPH" },
  { name: "Shelter", original_set: "ODY" },
  { name: "Shepherd of the Flock", original_set: "ELD" },
  { name: "Shepherd of the Lost", original_set: "ZEN" },
  { name: "Shieldhide Dragon", original_set: "DTK" },
  { name: "Sigil of the New Dawn", original_set: "UMA" },
  { name: "Silver Knight", original_set: "SCG" },
  { name: "Silverflame Squire", original_set: "ELD" },
  { name: "Sky Crier", original_set: "SNC" },
  { name: "Slaughter the Strong", original_set: "CMR" },
  { name: "Soltari Trooper", original_set: "TMP" },
  { name: "Soulfire Grand Master", original_set: "FRF" },
  { name: "Spectral Procession", original_set: "SHM" },
  { name: "Spirit en-Dal", original_set: "FUT" },
  { name: "Spirit Link", original_set: "10E" },
  { name: "Spirit Mantle", original_set: "M12" },
  { name: "Spirited Companion", original_set: "NEO" },
  { name: "Splendor Mare", original_set: "IKO" },
  { name: "Standard Bearer", original_set: "APC" },
  { name: "Starlit Angel", original_set: "POR" },
  { name: "Stasis Snare", original_set: "BFZ" },
  { name: "Steadfast Unicorn", original_set: "CLB" },
  { name: "Steppe Lynx", original_set: "ZEN" },
  { name: "Stir the Pride", original_set: "DST" },
  { name: "Stonecloaker", original_set: "PLC" },
  { name: "Stonehorn Dignitary", original_set: "M12" },
  { name: "Sunblade Angel", original_set: "CMM" },
  { name: "Sunder the Gateway", original_set: "MOM" },
  { name: "Sunscape Familiar", original_set: "PLS" },
  { name: "Supply Runners", original_set: "M21" },
  { name: "Surge of Salvation", original_set: "MOM" },
  { name: "Suture Priest", original_set: "NPH" },
  { name: "Swell of Courage", original_set: "MOR" },
  { name: "Swift Justice", original_set: "RTR" },
  { name: "Syndic of Tithes", original_set: "GTC" },
  { name: "Syr Alin, the Lion's Claw", original_set: "ELD" },
  { name: "Teferi's Honor Guard", original_set: "VIS" },
  { name: "Temple Acolyte", original_set: "P02" },
  { name: "Temporal Isolation", original_set: "TSP" },
  { name: "Tenacity", original_set: "SOI" },
  { name: "Teyo, the Shieldmage", original_set: "WAR" },
  { name: "The Birth of Meletis", original_set: "THB" },
  { name: "Thraben Watcher", original_set: "MH2" },
  { name: "Thunderous Orator", original_set: "STX" },
  { name: "Timeless Dragon", original_set: "MH2" },
  { name: "Tireless Tribe", original_set: "ODY" },
  { name: "To Arms!", original_set: "GPT" },
  { name: "Tormented Angel", original_set: "UDS" },
  { name: "Totem-Guide Hartebeest", original_set: "ROE" },
  { name: "Trap Runner", original_set: "MMQ" },
  { name: "Traveling Minister", original_set: "VOW" },
  { name: "Trostani's Judgment", original_set: "RTR" },
  { name: "True Love's Kiss", original_set: "ELD" },
  { name: "Twinblade Paladin", original_set: "M20" },
  { name: "Unbounded Potential", original_set: "MH2" },
  { name: "Valorous Stance", original_set: "CMR" },
  { name: "Valorous Steed", original_set: "M21" },
  { name: "Vanish into Eternity", original_set: "ONE" },
  { name: "Veteran Armorer", original_set: "RAV" },
  { name: "Vizier of Remedies", original_set: "AKH" },
  { name: "Wakestone Gargoyle", original_set: "CNS" },
  { name: "Wall of Glare", original_set: "UDS" },
  { name: "Wall of Swords", original_set: "POR" },
  { name: "Wanderer's Strike", original_set: "WAR" },
  { name: "War Priest of Thune", original_set: "M11" },
  { name: "Ward Sliver", original_set: "LGN" },
  { name: "Warrior en-Kor", original_set: "STH" },
  { name: "Whipcorder", original_set: "ONS" },
  { name: "Wispweaver Angel", original_set: "KLD" },
  { name: "Yosei, the Morning Star", original_set: "IMA" },
  { name: "You Hear Something on Watch", original_set: "AFR" },
  { name: "You're Confronted by Robbers", original_set: "CLB" },
  { name: "Youthful Valkyrie", original_set: "KHM" },

  // ── Blue (258) ─────────────────────────────────────
  { name: "Acquisition Octopus", original_set: "NEO" },
  { name: "Aetherize", original_set: "DDO" },
  { name: "Alchemist's Retrieval", original_set: "VOW" },
  { name: "Amoeboid Changeling", original_set: "J22" },
  { name: "An Offer You Can't Refuse", original_set: "SNC" },
  { name: "Annex", original_set: "ONS" },
  { name: "Aphetto Alchemist", original_set: "ONS" },
  { name: "Apprentice Sorcerer", original_set: "P02" },
  { name: "Aqueous Form", original_set: "THS" },
  { name: "Arcane Laboratory", original_set: "7ED" },
  { name: "Arcanis the Omnipotent", original_set: "DDN" },
  { name: "Battlewing Mystic", original_set: "DMU" },
  { name: "Belltoll Dragon", original_set: "DTK" },
  { name: "Berg Strider", original_set: "KHM" },
  { name: "Blatant Thievery", original_set: "E02" },
  { name: "Blink of an Eye", original_set: "DAR" },
  { name: "Body Double", original_set: "2X2" },
  { name: "Boomerang", original_set: "MIR" },
  { name: "Breakthrough", original_set: "TOR" },
  { name: "Brilliant Plan", original_set: "GS1" },
  { name: "Careful Study", original_set: "ODY" },
  { name: "Cephalid Broker", original_set: "ODY" },
  { name: "Cephalid Illusionist", original_set: "TOR" },
  { name: "Cerulean Wisps", original_set: "SHM" },
  { name: "Cerulean Wyvern", original_set: "MIR" },
  { name: "Chemister's Insight", original_set: "GRN" },
  { name: "Clever Impersonator", original_set: "KTK" },
  { name: "Cloak of Feathers", original_set: "POR" },
  { name: "Cloud Djinn", original_set: "WTH" },
  { name: "Cloud Spirit", original_set: "STH" },
  { name: "Coastal Piracy", original_set: "MMQ" },
  { name: "Code of Constraint", original_set: "RNA" },
  { name: "Cold-Water Snapper", original_set: "DAR" },
  { name: "Command of Unsummoning", original_set: "POR" },
  { name: "Complicate", original_set: "ONS" },
  { name: "Compulsion", original_set: "TOR" },
  { name: "Confound", original_set: "PLS" },
  { name: "Cryptic Command", original_set: "IMA" },
  { name: "Curiosity", original_set: "8ED" },
  { name: "Curious Obsession", original_set: "RIX" },
  { name: "Curse of Verbosity", original_set: "C17" },
  { name: "Dakra Mystic", original_set: "JOU" },
  { name: "Daring Saboteur", original_set: "SNC" },
  { name: "Deceiver Exarch", original_set: "NPH" },
  { name: "Deepchannel Mentor", original_set: "SHM" },
  { name: "Desertion", original_set: "CN2" },
  { name: "Diplomatic Escort", original_set: "MMQ" },
  { name: "Disrupt", original_set: "WTH" },
  { name: "Dissipate", original_set: "MIR" },
  { name: "Disturbing Conversion", original_set: "MOM" },
  { name: "Dive Down", original_set: "XLN" },
  { name: "Divide by Zero", original_set: "STX" },
  { name: "Dream Thrush", original_set: "INV" },
  { name: "Dreamscape Artist", original_set: "PLC" },
  { name: "Dreamtail Heron", original_set: "IKO" },
  { name: "Dress Down", original_set: "MH2" },
  { name: "Drift of Phantasms", original_set: "RAV" },
  { name: "Dukhara Peafowl", original_set: "KLD" },
  { name: "Echo Tracer", original_set: "LGN" },
  { name: "Echoing Truth", original_set: "DMU" },
  { name: "Eldrazi Skyspawner", original_set: "BFZ" },
  { name: "Enclave Cryptologist", original_set: "ROE" },
  { name: "Exhaustion", original_set: "POR" },
  { name: "Expel from Orazca", original_set: "RIX" },
  { name: "Experimental Augury", original_set: "ONE" },
  { name: "Fade Away", original_set: "EXO" },
  { name: "Faerie Seer", original_set: "MH1" },
  { name: "Faerie Swarm", original_set: "SHM" },
  { name: "False Summoning", original_set: "ME4" },
  { name: "Familiar's Ruse", original_set: "LRW" },
  { name: "Fatestitcher", original_set: "ALA" },
  { name: "Flash of Insight", original_set: "JUD" },
  { name: "Flight of Fancy", original_set: "RAV" },
  { name: "Flux", original_set: "POR" },
  { name: "Flux Channeler", original_set: "WAR" },
  { name: "Forbid", original_set: "EXO" },
  { name: "Force Spike", original_set: "DDJ" },
  { name: "Freed from the Real", original_set: "SOK" },
  { name: "Frogify", original_set: "2XM" },
  { name: "Frost Trickster", original_set: "STX" },
  { name: "Fumble", original_set: "BBD" },
  { name: "Ghostly Flicker", original_set: "KHM" },
  { name: "Gigadrowse", original_set: "GPT" },
  { name: "Grip of the Roil", original_set: "OGW" },
  { name: "Gudul Lurker", original_set: "DTK" },
  { name: "Guildpact Informant", original_set: "WAR" },
  { name: "Hada Spy Patrol", original_set: "CMA" },
  { name: "Halimar Depths", original_set: "DDM" },
  { name: "Halimar Wavewatch", original_set: "ROE" },
  { name: "Hard Evidence", original_set: "MH2" },
  { name: "Herald of Secret Streams", original_set: "XLN" },
  { name: "Horizon Scholar", original_set: "THS" },
  { name: "Horned Turtle", original_set: "POR" },
  { name: "Hydrolash", original_set: "GNT" },
  { name: "Ideas Unbound", original_set: "SOK" },
  { name: "Illusory Ambusher", original_set: "C15" },
  { name: "Invisible Stalker", original_set: "ZNR" },
  { name: "Irenicus's Vile Duplication", original_set: "CLB" },
  { name: "Jalira, Master Polymorphist", original_set: "A25" },
  { name: "Kasmina, Enigmatic Mentor", original_set: "WAR" },
  { name: "Kelpie Guide", original_set: "STX" },
  { name: "Killer Whale", original_set: "EXO" },
  { name: "Krovikan Sorcerer", original_set: "VMA" },
  { name: "Lazotep Plating", original_set: "WAR" },
  { name: "Leap", original_set: "STH" },
  { name: "Legacy's Allure", original_set: "TMP" },
  { name: "Legerdemain", original_set: "TMP" },
  { name: "Looter il-Kor", original_set: "TSP" },
  { name: "Majestic Metamorphosis", original_set: "SNC" },
  { name: "Mana Breach", original_set: "EXO" },
  { name: "Manipulate Fate", original_set: "INV" },
  { name: "Man-o'-War", original_set: "POR" },
  { name: "Master of Waves", original_set: "DDT" },
  { name: "Meeting of Minds", original_set: "MOM" },
  { name: "Mental Note", original_set: "JUD" },
  { name: "Merfolk of the Pearl Trident", original_set: "POR" },
  { name: "Merfolk Seastalkers", original_set: "ZEN" },
  { name: "Merfolk Thaumaturgist", original_set: "PLC" },
  { name: "Merfolk Trickster", original_set: "DAR" },
  { name: "Military Intelligence", original_set: "M15" },
  { name: "Mind Bend", original_set: "MIR" },
  { name: "Mirror Image", original_set: "M19" },
  { name: "Miscalculation", original_set: "ULG" },
  { name: "Mistblade Shinobi", original_set: "PCA" },
  { name: "Mistwalker", original_set: "KHM" },
  { name: "Moon-Circuit Hacker", original_set: "NEO" },
  { name: "Mothdust Changeling", original_set: "MOR" },
  { name: "Muddle the Mixture", original_set: "RAV" },
  { name: "Murmuring Mystic", original_set: "GRN" },
  { name: "Mystic Speculation", original_set: "FUT" },
  { name: "Mystic Subdual", original_set: "IKO" },
  { name: "Narcolepsy", original_set: "ROE" },
  { name: "Narset's Reversal", original_set: "WAR" },
  { name: "Nephalia Smuggler", original_set: "DDQ" },
  { name: "Neutralize", original_set: "IKO" },
  { name: "Nevermaker", original_set: "MOR" },
  { name: "Nexus of Fate", original_set: "M19" },
  { name: "Omen", original_set: "POR" },
  { name: "Omen of the Sea", original_set: "THB" },
  { name: "Oneirophage", original_set: "MH1" },
  { name: "Ophidian", original_set: "WTH" },
  { name: "Ophidian Eye", original_set: "TSP" },
  { name: "Ovinomancer", original_set: "DMR" },
  { name: "Owl Familiar", original_set: "POR" },
  { name: "Part the Waterveil", original_set: "BFZ" },
  { name: "Pemmin's Aura", original_set: "SCG" },
  { name: "Pendrell Drake", original_set: "USG" },
  { name: "Peregrine Drake", original_set: "USG" },
  { name: "Perilous Research", original_set: "MMA" },
  { name: "Piracy Charm", original_set: "PLC" },
  { name: "Pirate's Prize", original_set: "XLN" },
  { name: "Plated Seastrider", original_set: "SOM" },
  { name: "Plaxmanta", original_set: "DIS" },
  { name: "Pore Over the Pages", original_set: "SOI" },
  { name: "Power Sink", original_set: "MIR" },
  { name: "Probe", original_set: "INV" },
  { name: "Protect the Negotiators", original_set: "DMU" },
  { name: "Psychic Corrosion", original_set: "M19" },
  { name: "Rapid Hybridization", original_set: "STX" },
  { name: "Reality Shift", original_set: "NEO" },
  { name: "Referee Squad", original_set: "MOM" },
  { name: "Rescind", original_set: "USG" },
  { name: "Rewind", original_set: "USG" },
  { name: "Rise from the Tides", original_set: "GN2" },
  { name: "Rishadan Cutpurse", original_set: "MMQ" },
  { name: "Rite of Replication", original_set: "C14" },
  { name: "Ruin Crab", original_set: "ZNR" },
  { name: "Run Away Together", original_set: "CLB" },
  { name: "Rush of Knowledge", original_set: "SCG" },
  { name: "Rushing River", original_set: "PLS" },
  { name: "Scholar of the Ages", original_set: "M20" },
  { name: "Scion of Glaciers", original_set: "KTK" },
  { name: "Sea Scryer", original_set: "MIR" },
  { name: "Seal of Removal", original_set: "NEM" },
  { name: "Sejiri Merfolk", original_set: "WWK" },
  { name: "Serpentine Curve", original_set: "STX" },
  { name: "Serra Sphinx", original_set: "2XM" },
  { name: "Serum Visions", original_set: "STX" },
  { name: "Set Adrift", original_set: "KTK" },
  { name: "Shadow Rift", original_set: "TMP" },
  { name: "Shifting Sliver", original_set: "LGN" },
  { name: "Shimmering Glasskite", original_set: "BOK" },
  { name: "Shipwreck Dowser", original_set: "M21" },
  { name: "Shoreline Ranger", original_set: "SCG" },
  { name: "Shu Yun, the Silent Tempest", original_set: "FRF" },
  { name: "Silver Myr", original_set: "MRD" },
  { name: "Silvergill Douser", original_set: "LRW" },
  { name: "Siren Stormtamer", original_set: "XLN" },
  { name: "Skywatcher Adept", original_set: "ROE" },
  { name: "Snap", original_set: "ULG" },
  { name: "Sorcerous Sight", original_set: "POR" },
  { name: "Specimen Collector", original_set: "MH2" },
  { name: "Spectral Sailor", original_set: "M20" },
  { name: "Spellstutter Sprite", original_set: "LRW" },
  { name: "Spiketail Drake", original_set: "PCY" },
  { name: "Spin into Myth", original_set: "ARC" },
  { name: "Spined Megalodon", original_set: "M21" },
  { name: "Spreading Seas", original_set: "ZEN" },
  { name: "Sprite Noble", original_set: "EMA" },
  { name: "Startle", original_set: "MID" },
  { name: "Stinging Barrier", original_set: "MMQ" },
  { name: "Storm Crow", original_set: "POR" },
  { name: "Stormbound Geist", original_set: "DKA" },
  { name: "Striped Riverwinder", original_set: "HOU" },
  { name: "Sublime Epiphany", original_set: "M21" },
  { name: "Submerge", original_set: "NEM" },
  { name: "Suit Up", original_set: "NEO" },
  { name: "Supreme Will", original_set: "HOU" },
  { name: "Suq'Ata Firewalker", original_set: "MIR" },
  { name: "Surgical Skullbomb", original_set: "ONE" },
  { name: "Symbol of Unsummoning", original_set: "POR" },
  { name: "Talas Researcher", original_set: "ME4" },
  { name: "Talrand's Invocation", original_set: "M13" },
  { name: "Tasha's Hideous Laughter", original_set: "AFR" },
  { name: "Teferi, Mage of Zhalfir", original_set: "IMA" },
  { name: "Telekinetic Sliver", original_set: "TSP" },
  { name: "Tempest Caller", original_set: "XLN" },
  { name: "Tetsuko Umezawa, Fugitive", original_set: "DAR" },
  { name: "Tezzeret's Gambit", original_set: "NPH" },
  { name: "Thassa's Emissary", original_set: "THS" },
  { name: "Think Twice", original_set: "TSP" },
  { name: "Thought Courier", original_set: "5DN" },
  { name: "Thwart", original_set: "MMQ" },
  { name: "Tide Skimmer", original_set: "M21" },
  { name: "Time Ebb", original_set: "POR" },
  { name: "Time of Ice", original_set: "DAR" },
  { name: "Tolaria West", original_set: "FUT" },
  { name: "Tolarian Kraken", original_set: "M21" },
  { name: "Tolarian Terror", original_set: "DMU" },
  { name: "Tome Raider", original_set: "ELD" },
  { name: "Turnabout", original_set: "VMA" },
  { name: "Turtleshell Changeling", original_set: "LRW" },
  { name: "Twisted Image", original_set: "SOM" },
  { name: "Undo", original_set: "P02" },
  { name: "Unsubstantiate", original_set: "EMN" },
  { name: "Vedalken Dismisser", original_set: "RAV" },
  { name: "Viral Drake", original_set: "NPH" },
  { name: "Viscerid Deepwalker", original_set: "TSP" },
  { name: "Vodalian Hypnotist", original_set: "INV" },
  { name: "Voyager Drake", original_set: "WWK" },
  { name: "Wake Thrasher", original_set: "DDT" },
  { name: "Waker of Waves", original_set: "M21" },
  { name: "Wall of Tears", original_set: "STH" },
  { name: "Wash Away", original_set: "VOW" },
  { name: "Watcher for Tomorrow", original_set: "MH1" },
  { name: "Weatherseed Faeries", original_set: "ULG" },
  { name: "Web of Inertia", original_set: "JUD" },
  { name: "Whirler Rogue", original_set: "ORI" },
  { name: "Whirlpool Drake", original_set: "APC" },
  { name: "Wicked Slumber", original_set: "MOM" },
  { name: "Willbender", original_set: "DD2" },
  { name: "Windfall", original_set: "USG" },
  { name: "Windstorm Drake", original_set: "RNA" },
  { name: "Wing Splicer", original_set: "NPH" },
  { name: "Witching Well", original_set: "ELD" },
  { name: "Witness Protection", original_set: "SNC" },
  { name: "Wizard Class", original_set: "AFR" },
  { name: "Zephid's Embrace", original_set: "USG" },

  // ── Black (257) ────────────────────────────────────
  { name: "Ambition's Cost", original_set: "C15" },
  { name: "Aphetto Exterminator", original_set: "LGN" },
  { name: "Aphotic Wisps", original_set: "SHM" },
  { name: "Apprentice Necromancer", original_set: "UMA" },
  { name: "Archetype of Finality", original_set: "BNG" },
  { name: "Archfiend of Sorrows", original_set: "MH2" },
  { name: "Arrogant Vampire", original_set: "POR" },
  { name: "Attempted Murder", original_set: "UNF" },
  { name: "Audacious Thief", original_set: "M20" },
  { name: "Augur of Skulls", original_set: "FUT" },
  { name: "Bad Deal", original_set: "M21" },
  { name: "Bad Moon", original_set: "DD3" },
  { name: "Barter in Blood", original_set: "MRD" },
  { name: "Bastion of Remembrance", original_set: "IKO" },
  { name: "Battle-Rage Blessing", original_set: "DMU" },
  { name: "Beseech the Queen", original_set: "SHM" },
  { name: "Betrayal of Flesh", original_set: "MRD" },
  { name: "Bladewing's Thrall", original_set: "SCG" },
  { name: "Blessing of Leeches", original_set: "BOK" },
  { name: "Blightbeetle", original_set: "M20" },
  { name: "Blood Curdle", original_set: "IKO" },
  { name: "Blood Fountain", original_set: "VOW" },
  { name: "Blood Pact", original_set: "MID" },
  { name: "Blood Speaker", original_set: "CHK" },
  { name: "Bloodchief's Thirst", original_set: "ZNR" },
  { name: "Bloodthirsty Aerialist", original_set: "M20" },
  { name: "Bloodthrone Vampire", original_set: "ROE" },
  { name: "Blot Out", original_set: "MOM" },
  { name: "Bog Down", original_set: "PLS" },
  { name: "Boggart Harbinger", original_set: "LRW" },
  { name: "Bone Shards", original_set: "MH2" },
  { name: "Bone Shredder", original_set: "ULG" },
  { name: "Brood of Cockroaches", original_set: "VIS" },
  { name: "Bubbling Muck", original_set: "UDS" },
  { name: "Buried Alive", original_set: "WTH" },
  { name: "Bushmeat Poacher", original_set: "GN3" },
  { name: "Cabal Pit", original_set: "ODY" },
  { name: "Cackling Witch", original_set: "MMQ" },
  { name: "Call the Bloodline", original_set: "SOI" },
  { name: "Carrier Thrall", original_set: "2X2" },
  { name: "Cartouche of Ambition", original_set: "AKH" },
  { name: "Cast Down", original_set: "2XM" },
  { name: "Chain of Smog", original_set: "ONS" },
  { name: "Chainer's Edict", original_set: "TOR" },
  { name: "Charcoal Diamond", original_set: "MIR" },
  { name: "Chittering Rats", original_set: "J22" },
  { name: "Cling to Dust", original_set: "THB" },
  { name: "Coffin Queen", original_set: "TPR" },
  { name: "Corpse Augur", original_set: "C15" },
  { name: "Corpse Connoisseur", original_set: "ALA" },
  { name: "Corpse Harvester", original_set: "LGN" },
  { name: "Corrupt", original_set: "USG" },
  { name: "Crippling Fatigue", original_set: "TOR" },
  { name: "Crypt Champion", original_set: "GK2" },
  { name: "Crypt Sliver", original_set: "LGN" },
  { name: "Curse of Shallow Graves", original_set: "C13" },
  { name: "Dakmor Plague", original_set: "P02" },
  { name: "Dark Triumph", original_set: "NEM" },
  { name: "Dauthi Embrace", original_set: "TMP" },
  { name: "Dauthi Horror", original_set: "TMP" },
  { name: "Dauthi Trapper", original_set: "STH" },
  { name: "Dauthi Voidwalker", original_set: "MH2" },
  { name: "Davriel, Rogue Shadowmage", original_set: "WAR" },
  { name: "Dead Weight", original_set: "GRN" },
  { name: "Deadly Dispute", original_set: "AFR" },
  { name: "Death Pulse", original_set: "ONS" },
  { name: "Deathgreeter", original_set: "DDD" },
  { name: "Deepwood Legate", original_set: "MMQ" },
  { name: "Despondency", original_set: "USG" },
  { name: "Diabolic Servitude", original_set: "PD3" },
  { name: "Diabolic Tutor", original_set: "ODY" },
  { name: "Dimir House Guard", original_set: "RAV" },
  { name: "Diregraf Ghoul", original_set: "ISD" },
  { name: "Diregraf Horde", original_set: "MID" },
  { name: "Disturbed Burial", original_set: "TMP" },
  { name: "Dockside Chef", original_set: "NEO" },
  { name: "Dreadhound", original_set: "MID" },
  { name: "Dusk Mangler", original_set: "SNC" },
  { name: "Elspeth's Nightmare", original_set: "THB" },
  { name: "Endless Scream", original_set: "TMP" },
  { name: "Epic Downfall", original_set: "ELD" },
  { name: "Essence Extraction", original_set: "KLD" },
  { name: "Evil Eye of Urborg", original_set: "TSP" },
  { name: "Expunge", original_set: "USG" },
  { name: "Falkenrath Noble", original_set: "VOW" },
  { name: "Feast or Famine", original_set: "DDJ" },
  { name: "Feed the Swarm", original_set: "SCD" },
  { name: "Feign Death", original_set: "AFR" },
  { name: "Fell Specter", original_set: "M19" },
  { name: "Fell Stinger", original_set: "VOW" },
  { name: "Feral Shadow", original_set: "POR" },
  { name: "Filth", original_set: "JUD" },
  { name: "Fledgling Djinn", original_set: "WTH" },
  { name: "Fleshbag Marauder", original_set: "CMD" },
  { name: "Flesh-Eater Imp", original_set: "MBS" },
  { name: "Footbottom Feast", original_set: "LRW" },
  { name: "Footsteps of the Goryo", original_set: "SOK" },
  { name: "Foulmire Knight", original_set: "MOM" },
  { name: "Gatekeeper of Malakir", original_set: "ZEN" },
  { name: "Ghost-Lit Stalker", original_set: "SOK" },
  { name: "Gilt-Leaf Winnower", original_set: "CMR" },
  { name: "Gloom Sower", original_set: "M21" },
  { name: "Gloomfang Mauler", original_set: "MOM" },
  { name: "Go Blank", original_set: "STX" },
  { name: "Graveshifter", original_set: "MOM" },
  { name: "Grim Bounty", original_set: "AFR" },
  { name: "Grim Hireling", original_set: "AFR" },
  { name: "Grimdancer", original_set: "IKO" },
  { name: "Hand of Death", original_set: "P02" },
  { name: "Havoc Demon", original_set: "EMA" },
  { name: "Heartless Act", original_set: "IKO" },
  { name: "Hell's Caretaker", original_set: "A25" },
  { name: "Hero's Downfall", original_set: "VOW" },
  { name: "Ill-Gotten Inheritance", original_set: "RNA" },
  { name: "Incremental Blight", original_set: "HOP" },
  { name: "Indulgent Tormentor", original_set: "IMA" },
  { name: "Injector Crocodile", original_set: "MOM" },
  { name: "Kaya's Ghostform", original_set: "WAR" },
  { name: "Keeper of the Dead", original_set: "EXO" },
  { name: "Lampad of Death's Vigil", original_set: "THB" },
  { name: "Lash of Malice", original_set: "STX" },
  { name: "Liliana, Death Mage", original_set: "M21" },
  { name: "Liliana's Caress", original_set: "M11" },
  { name: "Liliana's Devotee", original_set: "M21" },
  { name: "Liliana's Specter", original_set: "M11" },
  { name: "Mad Auntie", original_set: "MMA" },
  { name: "Marchesa's Decree", original_set: "CN2" },
  { name: "Markov Baron", original_set: "MOM" },
  { name: "Marsh Flitter", original_set: "LRW" },
  { name: "Massacre", original_set: "NEM" },
  { name: "Merciless Executioner", original_set: "FRF" },
  { name: "Mesmeric Fiend", original_set: "TOR" },
  { name: "Mindstab", original_set: "TSP" },
  { name: "Mindwrack Harpy", original_set: "THB" },
  { name: "Mischievous Poltergeist", original_set: "WTH" },
  { name: "Moan of the Unhallowed", original_set: "UMA" },
  { name: "Mogis's Favor", original_set: "THB" },
  { name: "Moment of Defiance", original_set: "BRO" },
  { name: "Moonglove Changeling", original_set: "MOR" },
  { name: "Morbid Opportunist", original_set: "MID" },
  { name: "Murderous Rider", original_set: "ELD" },
  { name: "Necrologia", original_set: "7ED" },
  { name: "Nekrataal", original_set: "DDM" },
  { name: "Nezumi Graverobber", original_set: "CHK" },
  { name: "Nezumi Prowler", original_set: "NEO" },
  { name: "Nightfire Giant", original_set: "M15" },
  { name: "Nirkana Cutthroat", original_set: "ROE" },
  { name: "Noxious Ghoul", original_set: "LGN" },
  { name: "Oblivion Strike", original_set: "OGW" },
  { name: "Olivia's Bloodsworn", original_set: "SOI" },
  { name: "Order of Midnight", original_set: "ELD" },
  { name: "Order of Yawgmoth", original_set: "USG" },
  { name: "Orzhov Enforcer", original_set: "RNA" },
  { name: "Oubliette", original_set: "2XM" },
  { name: "Paragon of Open Graves", original_set: "M15" },
  { name: "Pawn of Ulamog", original_set: "ROE" },
  { name: "Peat Bog", original_set: "MMQ" },
  { name: "Peer into the Abyss", original_set: "M21" },
  { name: "Phyrexian Gargantua", original_set: "APC" },
  { name: "Phyrexian Scriptures", original_set: "DOM" },
  { name: "Plague Engineer", original_set: "MH1" },
  { name: "Plague Spitter", original_set: "INV" },
  { name: "Power Word Kill", original_set: "AFR" },
  { name: "Prakhata Pillar-Bug", original_set: "KLD" },
  { name: "Predatory Nightstalker", original_set: "VMA" },
  { name: "Priest of Gix", original_set: "DDE" },
  { name: "Primeval Shambler", original_set: "MMQ" },
  { name: "Public Execution", original_set: "M13" },
  { name: "Puppet Conjurer", original_set: "ALA" },
  { name: "Putrid Goblin", original_set: "MH1" },
  { name: "Raiders' Wake", original_set: "XLN" },
  { name: "Rain of Filth", original_set: "USG" },
  { name: "Raise Dead", original_set: "P02" },
  { name: "Raven's Crime", original_set: "EVE" },
  { name: "Reanimate", original_set: "TMP" },
  { name: "Reaper's Talisman", original_set: "AFR" },
  { name: "Reaping the Graves", original_set: "SCG" },
  { name: "Reckoner's Bargain", original_set: "NEO" },
  { name: "Revenge of Ravens", original_set: "ELD" },
  { name: "Rite of Consumption", original_set: "SHM" },
  { name: "Rotting Regisaur", original_set: "M20" },
  { name: "Rush of Vitality", original_set: "KLD" },
  { name: "Ruthless Knave", original_set: "XLN" },
  { name: "Savage Gorger", original_set: "M20" },
  { name: "Scrapwork Rager", original_set: "BRO" },
  { name: "Sedgemoor Witch", original_set: "STX" },
  { name: "Sengir Autocrat", original_set: "EMA" },
  { name: "Sever Soul", original_set: "MMQ" },
  { name: "Severed Strands", original_set: "GRN" },
  { name: "Shade's Form", original_set: "TOR" },
  { name: "Shadow Prophecy", original_set: "DMU" },
  { name: "Shambling Ghast", original_set: "AFR" },
  { name: "Sheoldred's Edict", original_set: "ONE" },
  { name: "Shepherd of Rot", original_set: "ONS" },
  { name: "Shoreline Salvager", original_set: "WWK" },
  { name: "Sign in Blood", original_set: "M10" },
  { name: "Skeletal Changeling", original_set: "LRW" },
  { name: "Skeletal Wurm", original_set: "ROE" },
  { name: "Skinthinner", original_set: "LGN" },
  { name: "Skirge Familiar", original_set: "USG" },
  { name: "Skull Raid", original_set: "KHM" },
  { name: "Skullport Merchant", original_set: "AFR" },
  { name: "Skullsnatcher", original_set: "BOK" },
  { name: "Sling-Gang Lieutenant", original_set: "MH1" },
  { name: "Soul Snuffers", original_set: "EVE" },
  { name: "Souldrinker", original_set: "TMP" },
  { name: "Spark Reaper", original_set: "WAR" },
  { name: "Spectral Sliver", original_set: "LGN" },
  { name: "Steal Strength", original_set: "PCY" },
  { name: "Stir the Sands", original_set: "AKH" },
  { name: "Strands of Night", original_set: "WTH" },
  { name: "Stromgald Crusader", original_set: "CSP" },
  { name: "Stupor", original_set: "MIR" },
  { name: "Suffocating Fumes", original_set: "IKO" },
  { name: "Summon Undead", original_set: "CLB" },
  { name: "Supernatural Stamina", original_set: "GN3" },
  { name: "Swarm of Rats", original_set: "P02" },
  { name: "Syr Konrad, the Grim", original_set: "ELD" },
  { name: "Terror", original_set: "10E" },
  { name: "The Haunt of Hightower", original_set: "RNA" },
  { name: "Thirsting Bloodlord", original_set: "M20" },
  { name: "Throat Slitter", original_set: "BOK" },
  { name: "Thrull Parasite", original_set: "GTC" },
  { name: "Tortured Existence", original_set: "STH" },
  { name: "Tourach, Dread Cantor", original_set: "MH2" },
  { name: "Twisted Abomination", original_set: "SCG" },
  { name: "Ultimate Price", original_set: "GK2" },
  { name: "Unburial Rites", original_set: "ISD" },
  { name: "Undead Augur", original_set: "MH1" },
  { name: "Undercity Informer", original_set: "GTC" },
  { name: "Underworld Hermit", original_set: "MH2" },
  { name: "Unearth", original_set: "ULG" },
  { name: "Unexpected Fangs", original_set: "IKO" },
  { name: "Unseal the Necropolis", original_set: "MOM" },
  { name: "Unspeakable Symbol", original_set: "SCG" },
  { name: "Urborg Repossession", original_set: "DMU" },
  { name: "Vampire of the Dire Moon", original_set: "M20" },
  { name: "Vampiric Link", original_set: "PLC" },
  { name: "Vendetta", original_set: "MMQ" },
  { name: "Vile Requiem", original_set: "USG" },
  { name: "Vindictive Vampire", original_set: "RNA" },
  { name: "Virtue's Ruin", original_set: "POR" },
  { name: "Virus Beetle", original_set: "NEO" },
  { name: "Void Beckoner", original_set: "IKO" },
  { name: "Vow of Malice", original_set: "CM2" },
  { name: "Wall of Blood", original_set: "MRD" },
  { name: "Wall of Corpses", original_set: "MIR" },
  { name: "Weaponcraft Enthusiast", original_set: "KLD" },
  { name: "Wicked Pact", original_set: "ME4" },
  { name: "Witch of the Moors", original_set: "M21" },
  { name: "Withered Wretch", original_set: "LGN" },
  { name: "You Are Already Dead", original_set: "NEO" },
  { name: "Young Necromancer", original_set: "MH2" },
  { name: "Zombie Cutthroat", original_set: "SCG" },
  { name: "Zombie Infestation", original_set: "ODY" },
  { name: "Zulaport Cutthroat", original_set: "GNT" },
  { name: "Zulaport Enforcer", original_set: "ROE" },

  // ── Red (255) ──────────────────────────────────────
  { name: "About Face", original_set: "ULG" },
  { name: "Abrade", original_set: "2XM" },
  { name: "Acidic Soil", original_set: "USG" },
  { name: "Aftershock", original_set: "TMP" },
  { name: "Alena, Kessig Trapper", original_set: "CMR" },
  { name: "Anarchist", original_set: "ODY" },
  { name: "Anax, Hardened in the Forge", original_set: "THB" },
  { name: "Ancient Hydra", original_set: "NEM" },
  { name: "Anger", original_set: "JUD" },
  { name: "Arc Lightning", original_set: "USG" },
  { name: "Ardent Elementalist", original_set: "MID" },
  { name: "Arms Dealer", original_set: "MMQ" },
  { name: "Axgard Cavalry", original_set: "KHM" },
  { name: "Balduvian Warlord", original_set: "CSP" },
  { name: "Barbed Batterfist", original_set: "ONE" },
  { name: "Battle Cry Goblin", original_set: "AFR" },
  { name: "Battle Squadron", original_set: "EMA" },
  { name: "Berserkers' Onslaught", original_set: "DTK" },
  { name: "Besmirch", original_set: "CN2" },
  { name: "Big Score", original_set: "SNC" },
  { name: "Bitter Reunion", original_set: "BRO" },
  { name: "Blade Sliver", original_set: "LGN" },
  { name: "Blaze", original_set: "POR" },
  { name: "Blazing Crescendo", original_set: "ONE" },
  { name: "Blood Frenzy", original_set: "TMP" },
  { name: "Blood Knight", original_set: "PLC" },
  { name: "Bloodmark Mentor", original_set: "DPA" },
  { name: "Boarding Party", original_set: "CMR" },
  { name: "Boldwyr Intimidator", original_set: "MOR" },
  { name: "Bolt Bend", original_set: "WAR" },
  { name: "Bonecrusher Giant", original_set: "ELD" },
  { name: "Bonus Round", original_set: "BBD" },
  { name: "Boots of Speed", original_set: "AFR" },
  { name: "Breath of Darigaaz", original_set: "INV" },
  { name: "Bronzeplate Boar", original_set: "NEO" },
  { name: "Brute Force", original_set: "PLC" },
  { name: "Burning Cloak", original_set: "POR" },
  { name: "Burning Palm Efreet", original_set: "MIR" },
  { name: "Burning Prophet", original_set: "WAR" },
  { name: "By Force", original_set: "AKH" },
  { name: "Cavalier of Flame", original_set: "M20" },
  { name: "Chandra, Novice Pyromancer", original_set: "M20" },
  { name: "Changeling Berserker", original_set: "LRW" },
  { name: "Chaos Channeler", original_set: "AFR" },
  { name: "Charging Tuskodon", original_set: "RIX" },
  { name: "Cheering Fanatic", original_set: "BBD" },
  { name: "Cinder Cloud", original_set: "MIR" },
  { name: "Cone of Flame", original_set: "WTH" },
  { name: "Conspicuous Snoop", original_set: "M21" },
  { name: "Convulsing Licid", original_set: "STH" },
  { name: "Cragsmasher Yeti", original_set: "MOM" },
  { name: "Crimson Fleet Commodore", original_set: "CMR" },
  { name: "Crimson Wisps", original_set: "SHM" },
  { name: "Dark-Dweller Oracle", original_set: "2X2" },
  { name: "Dead // Gone", original_set: "PLC" },
  { name: "Desert of the Fervent", original_set: "STX" },
  { name: "Dragon Mage", original_set: "M20" },
  { name: "Dwarven Blastminer", original_set: "ONS" },
  { name: "Dwarven Hammer", original_set: "KHM" },
  { name: "Dwarven Miner", original_set: "MIR" },
  { name: "Dwarven Recruiter", original_set: "ODY" },
  { name: "Electric Revelation", original_set: "J22" },
  { name: "Electrickery", original_set: "GK1" },
  { name: "Electrostatic Field", original_set: "GRN" },
  { name: "Embereth Shieldbreaker", original_set: "ELD" },
  { name: "Empty the Warrens", original_set: "DDS" },
  { name: "Experimental Synthesizer", original_set: "NEO" },
  { name: "Explosive Welcome", original_set: "STX" },
  { name: "Exuberant Fuseling", original_set: "ONE" },
  { name: "Faithless Salvaging", original_set: "MH2" },
  { name: "Falkenrath Celebrants", original_set: "VOW" },
  { name: "Falter", original_set: "USG" },
  { name: "Fanatic of Mogis", original_set: "THS" },
  { name: "Fanning the Flames", original_set: "STH" },
  { name: "Fearless Skald", original_set: "MOM" },
  { name: "Fiery Impulse", original_set: "ORI" },
  { name: "Fire Imp", original_set: "POR" },
  { name: "Fire Servant", original_set: "PD2" },
  { name: "Fire-Belly Changeling", original_set: "LRW" },
  { name: "Fireblast", original_set: "VIS" },
  { name: "Firecat Blitz", original_set: "JUD" },
  { name: "Fireslinger", original_set: "TMP" },
  { name: "Firewing Phoenix", original_set: "UMA" },
  { name: "First Day of Class", original_set: "STX" },
  { name: "Fists of Flame", original_set: "CMR" },
  { name: "Flame Elemental", original_set: "MIR" },
  { name: "Flame Javelin", original_set: "DD2" },
  { name: "Flame Slash", original_set: "DDK" },
  { name: "Flame Wave", original_set: "STH" },
  { name: "Flaring Pain", original_set: "JUD" },
  { name: "Flowstone Hellion", original_set: "STH" },
  { name: "Footfall Crater", original_set: "IKO" },
  { name: "Forked Lightning", original_set: "ME3" },
  { name: "Frenzied Fugue", original_set: "C16" },
  { name: "Frenzied Saddlebrute", original_set: "CMR" },
  { name: "Furious Rise", original_set: "THB" },
  { name: "Furnace Punisher", original_set: "ONE" },
  { name: "Fury Sliver", original_set: "TSP" },
  { name: "Gathan Raiders", original_set: "FUT" },
  { name: "Geistblast", original_set: "SOI" },
  { name: "Gempalm Incinerator", original_set: "DDT" },
  { name: "Ghitu Slinger", original_set: "ULG" },
  { name: "Giant Cindermaw", original_set: "BRO" },
  { name: "Glarewielder", original_set: "LRW" },
  { name: "Go for Blood", original_set: "J22" },
  { name: "Goblin Chainwhirler", original_set: "DAR" },
  { name: "Goblin Cratermaker", original_set: "GRN" },
  { name: "Goblin Gardener", original_set: "UDS" },
  { name: "Goblin Goliath", original_set: "GNT" },
  { name: "Goblin Grenadiers", original_set: "WTH" },
  { name: "Goblin Instigator", original_set: "M19" },
  { name: "Goblin Matron", original_set: "USG" },
  { name: "Goblin Offensive", original_set: "USG" },
  { name: "Goblin Taskmaster", original_set: "ONS" },
  { name: "Goblin Wardriver", original_set: "MBS" },
  { name: "Goblin Wizardry", original_set: "M21" },
  { name: "Goblinslide", original_set: "KTK" },
  { name: "Gorilla Shaman", original_set: "MH2" },
  { name: "Grab the Reins", original_set: "MRD" },
  { name: "Ground Rift", original_set: "TSP" },
  { name: "Hatchet Bully", original_set: "EVE" },
  { name: "Havoc Jester", original_set: "M21" },
  { name: "Hazoret the Fervent", original_set: "AKH" },
  { name: "Hellspark Elemental", original_set: "DDK" },
  { name: "Hematite Golem", original_set: "MRD" },
  { name: "Hoarding Dragon", original_set: "IMA" },
  { name: "Hoarding Ogre", original_set: "AFR" },
  { name: "Honor the God-Pharaoh", original_set: "WAR" },
  { name: "Hordeling Outburst", original_set: "A25" },
  { name: "Humble Defector", original_set: "FRF" },
  { name: "Immolating Souleater", original_set: "NPH" },
  { name: "Incinerate", original_set: "MIR" },
  { name: "Inspired Tinkering", original_set: "CLB" },
  { name: "Insult // Injury", original_set: "AKH" },
  { name: "Invigorated Rampage", original_set: "AER" },
  { name: "Ire Shaman", original_set: "A25" },
  { name: "Jaya, Venerated Firemage", original_set: "WAR" },
  { name: "Keldon Champion", original_set: "UDS" },
  { name: "Keldon Strike Team", original_set: "DMU" },
  { name: "Kyren Negotiations", original_set: "MMQ" },
  { name: "Lava Dart", original_set: "JUD" },
  { name: "Lava Hounds", original_set: "WTH" },
  { name: "Lesser Gargadon", original_set: "PCY" },
  { name: "Light Up the Stage", original_set: "RNA" },
  { name: "Lightning Mauler", original_set: "AVR" },
  { name: "Lunar Frenzy", original_set: "MID" },
  { name: "Mad Ratter", original_set: "ELD" },
  { name: "Magmatic Insight", original_set: "ORI" },
  { name: "Magmaw", original_set: "UMA" },
  { name: "Mercadia's Downfall", original_set: "MMQ" },
  { name: "Merchant of the Vale", original_set: "ELD" },
  { name: "Meria's Outrider", original_set: "DMU" },
  { name: "Mogg Conscripts", original_set: "TMP" },
  { name: "Mogg Infestation", original_set: "TPR" },
  { name: "Mogg Maniac", original_set: "STH" },
  { name: "Mogg Raider", original_set: "TMP" },
  { name: "Molten Birth", original_set: "M14" },
  { name: "Muxus, Goblin Grandee", original_set: "M21" },
  { name: "Needle Drop", original_set: "LRW" },
  { name: "Needletooth Raptor", original_set: "RIX" },
  { name: "Nimble Birdsticker", original_set: "M20" },
  { name: "Ogre Arsonist", original_set: "P02" },
  { name: "Onslaught", original_set: "EXO" },
  { name: "Orcish Lumberjack", original_set: "DDL" },
  { name: "Orcish Settlers", original_set: "WTH" },
  { name: "Outmaneuver", original_set: "USG" },
  { name: "Pandemonium", original_set: "TPR" },
  { name: "Pardic Collaborator", original_set: "TOR" },
  { name: "Pillaging Horde", original_set: "POR" },
  { name: "Pitchstone Wall", original_set: "TOR" },
  { name: "Plundering Barbarian", original_set: "AFR" },
  { name: "Price of Glory", original_set: "ODY" },
  { name: "Price of Progress", original_set: "EXO" },
  { name: "Punishing Fire", original_set: "DDG" },
  { name: "Purifying Dragon", original_set: "MID" },
  { name: "Pyreheart Wolf", original_set: "DKA" },
  { name: "Pyrewild Shaman", original_set: "MM3" },
  { name: "Pyrite Spellbomb", original_set: "DDU" },
  { name: "Pyrohemia", original_set: "PLC" },
  { name: "Pyrokinesis", original_set: "DDL" },
  { name: "Rabbit Battery", original_set: "NEO" },
  { name: "Raging Minotaur", original_set: "POR" },
  { name: "Ramunap Ruins", original_set: "HOU" },
  { name: "Rapacious Dragon", original_set: "2XM" },
  { name: "Rapacious One", original_set: "ROE" },
  { name: "Reckless Abandon", original_set: "UDS" },
  { name: "Reckless Barbarian", original_set: "CLB" },
  { name: "Reckless Bushwhacker", original_set: "OGW" },
  { name: "Reckless Charge", original_set: "ODY" },
  { name: "Reckless Impulse", original_set: "VOW" },
  { name: "Reckless Rage", original_set: "RIX" },
  { name: "Rending Volley", original_set: "DTK" },
  { name: "Renegade Warlord", original_set: "TMP" },
  { name: "Ricochet Trap", original_set: "WWK" },
  { name: "Rimrock Knight", original_set: "ELD" },
  { name: "Rites of Initiation", original_set: "ODY" },
  { name: "Rock Slide", original_set: "VIS" },
  { name: "Rupture", original_set: "NEM" },
  { name: "Sabertooth Wyvern", original_set: "EXO" },
  { name: "Sarkhan's Whelp", original_set: "M19" },
  { name: "Scoria Cat", original_set: "PCY" },
  { name: "Scourge Devil", original_set: "MM3" },
  { name: "Scrapwork Mutt", original_set: "BRO" },
  { name: "Seal of Fire", original_set: "NEM" },
  { name: "Searing Blaze", original_set: "WWK" },
  { name: "Searing Spear", original_set: "M13" },
  { name: "Seething Anger", original_set: "STH" },
  { name: "Shivan Raptor", original_set: "USG" },
  { name: "Shiv's Embrace", original_set: "USG" },
  { name: "Shower of Coals", original_set: "ODY" },
  { name: "Shredded Sails", original_set: "IKO" },
  { name: "Skewer the Critics", original_set: "RNA" },
  { name: "Slavering Nulls", original_set: "DDH" },
  { name: "Smash to Dust", original_set: "DMU" },
  { name: "Solar Blast", original_set: "ONS" },
  { name: "Sparksmith", original_set: "ONS" },
  { name: "Spellshock", original_set: "EXO" },
  { name: "Spitebellows", original_set: "MOR" },
  { name: "Spiteful Prankster", original_set: "M21" },
  { name: "Spitting Earth", original_set: "P02" },
  { name: "Sticky Fingers", original_set: "SNC" },
  { name: "Stingscourger", original_set: "PLC" },
  { name: "Stoke the Flames", original_set: "M15" },
  { name: "Storm Caller", original_set: "M21" },
  { name: "Storm-Kiln Artist", original_set: "STX" },
  { name: "Strafe", original_set: "PLS" },
  { name: "Sure Strike", original_set: "GRN" },
  { name: "Swarming Goblins", original_set: "AFR" },
  { name: "Swelter", original_set: "JUD" },
  { name: "Thermo-Alchemist", original_set: "EMN" },
  { name: "Thermopod", original_set: "CSP" },
  { name: "Thopter Engineer", original_set: "ORI" },
  { name: "Thunderclap", original_set: "MMQ" },
  { name: "Thunderwave", original_set: "CLB" },
  { name: "Tibalt, Rakish Instigator", original_set: "WAR" },
  { name: "Tin Street Hooligan", original_set: "GPT" },
  { name: "Titan's Strength", original_set: "THS" },
  { name: "Toggo, Goblin Weaponsmith", original_set: "CMR" },
  { name: "Torch Breath", original_set: "SNC" },
  { name: "Torrent of Fire", original_set: "SCG" },
  { name: "Twinferno", original_set: "DMU" },
  { name: "Two-Handed Axe", original_set: "CLB" },
  { name: "Unchained Berserker", original_set: "M20" },
  { name: "Unexpected Windfall", original_set: "AFR" },
  { name: "Varchild, Betrayer of Kjeldor", original_set: "C18" },
  { name: "Violent Eruption", original_set: "TOR" },
  { name: "Volatile Claws", original_set: "MH1" },
  { name: "Volcanic Geyser", original_set: "MIR" },
  { name: "Volcanic Hammer", original_set: "8ED" },
  { name: "Volcanic Spite", original_set: "MOM" },
  { name: "Voldaren Epicure", original_set: "VOW" },
  { name: "Wrenn's Resolve", original_set: "MOM" },
  { name: "You Find Some Prisoners", original_set: "AFR" },
  { name: "Young Red Dragon", original_set: "CLB" },
  { name: "Zada, Hedron Grinder", original_set: "A25" },

  // ── Green (256) ────────────────────────────────────
  { name: "Abzan Beastmaster", original_set: "FRF" },
  { name: "Alluring Scent", original_set: "ME4" },
  { name: "Ambush Commander", original_set: "EVG" },
  { name: "Ancestral Mask", original_set: "MMQ" },
  { name: "Ancient Silverback", original_set: "M15" },
  { name: "Argothian Elder", original_set: "USG" },
  { name: "Argothian Opportunist", original_set: "BRO" },
  { name: "Armorcraft Judge", original_set: "KLD" },
  { name: "Arrogant Wurm", original_set: "TOR" },
  { name: "Assault Formation", original_set: "IMA" },
  { name: "Atraxa's Fall", original_set: "MOM" },
  { name: "Avenging Druid", original_set: "EXO" },
  { name: "Axebane Guardian", original_set: "RTR" },
  { name: "Baloth Woodcrasher", original_set: "ZEN" },
  { name: "Bassara Tower Archer", original_set: "JOU" },
  { name: "Beast Attack", original_set: "ODY" },
  { name: "Bellowing Tanglewurm", original_set: "SOM" },
  { name: "Biogenic Upgrade", original_set: "RNA" },
  { name: "Blanchwood Prowler", original_set: "BRO" },
  { name: "Blight Mamba", original_set: "SOM" },
  { name: "Blightwidow", original_set: "MBS" },
  { name: "Bloom Hulk", original_set: "WAR" },
  { name: "Blossoming Defense", original_set: "KLD" },
  { name: "Bookwurm", original_set: "STX" },
  { name: "Briar Patch", original_set: "MMQ" },
  { name: "Broken Wings", original_set: "KHM" },
  { name: "Brood Monitor", original_set: "BFZ" },
  { name: "Broodhatch Nantuko", original_set: "ONS" },
  { name: "Bushwhack", original_set: "BRO" },
  { name: "Call of the Herd", original_set: "DMR" },
  { name: "Canopy Surge", original_set: "INV" },
  { name: "Cartouche of Strength", original_set: "AKH" },
  { name: "Challenger Troll", original_set: "WAR" },
  { name: "Changeling Titan", original_set: "LRW" },
  { name: "Charge Through", original_set: "STX" },
  { name: "Compost", original_set: "UDS" },
  { name: "Crashing Boars", original_set: "EXO" },
  { name: "Cudgel Troll", original_set: "M10" },
  { name: "Curse of Predation", original_set: "C13" },
  { name: "Cytoplast Root-Kin", original_set: "MM2" },
  { name: "Dawntreader Elk", original_set: "DKA" },
  { name: "Deep Reconnaissance", original_set: "ODY" },
  { name: "Deglamer", original_set: "MOR" },
  { name: "Destiny Spinner", original_set: "THB" },
  { name: "Devoted Druid", original_set: "SHM" },
  { name: "Diligent Farmhand", original_set: "ODY" },
  { name: "Dread Linnorm", original_set: "CLB" },
  { name: "Dreampod Druid", original_set: "PC2" },
  { name: "Druid's Familiar", original_set: "AVR" },
  { name: "Drumhunter", original_set: "ALA" },
  { name: "Earthshaker Giant", original_set: "GN2" },
  { name: "Elemental Bond", original_set: "ORI" },
  { name: "Elephant Ambush", original_set: "ODY" },
  { name: "Elite Cat Warrior", original_set: "POR" },
  { name: "Elven Bow", original_set: "KHM" },
  { name: "Elven Riders", original_set: "ONS" },
  { name: "Elvish Harbinger", original_set: "EVG" },
  { name: "Elvish Ranger", original_set: "POR" },
  { name: "Enlarge", original_set: "M14" },
  { name: "Evolution Charm", original_set: "PLC" },
  { name: "Evolution Sage", original_set: "WAR" },
  { name: "Evolutionary Escalation", original_set: "C16" },
  { name: "Fae Offering", original_set: "MH2" },
  { name: "Fangren Marauder", original_set: "MBS" },
  { name: "Far Wanderings", original_set: "TOR" },
  { name: "Feral Hydra", original_set: "BBD" },
  { name: "Fortifying Draught", original_set: "STX" },
  { name: "Frog Tongue", original_set: "TMP" },
  { name: "Fyndhorn Elder", original_set: "8ED" },
  { name: "Fyndhorn Elves", original_set: "CMR" },
  { name: "Fynn, the Fangbearer", original_set: "KHM" },
  { name: "Gaea's Anthem", original_set: "MM3" },
  { name: "Gaea's Embrace", original_set: "USG" },
  { name: "Gaea's Gift", original_set: "BRO" },
  { name: "Gamekeeper", original_set: "UDS" },
  { name: "Garruk's Packleader", original_set: "M11" },
  { name: "Garruk's Uprising", original_set: "M21" },
  { name: "Gemhide Sliver", original_set: "TSP" },
  { name: "Gigantosaurus", original_set: "M19" },
  { name: "Golden Bear", original_set: "P02" },
  { name: "Golgari Grave-Troll", original_set: "UMA" },
  { name: "Great Oak Guardian", original_set: "C19" },
  { name: "Grizzly Fate", original_set: "JUD" },
  { name: "Grothama, All-Devouring", original_set: "BBD" },
  { name: "Harvester Druid", original_set: "JUD" },
  { name: "Haywire Mite", original_set: "BRO" },
  { name: "Heart Warden", original_set: "UDS" },
  { name: "Hedge Troll", original_set: "PLC" },
  { name: "Heroes' Bane", original_set: "IMA" },
  { name: "Horned Sliver", original_set: "TMP" },
  { name: "Hunger of the Howlpack", original_set: "DKA" },
  { name: "Hunted Wumpus", original_set: "MMQ" },
  { name: "Hunter's Edge", original_set: "M21" },
  { name: "Hunter's Mark", original_set: "AFR" },
  { name: "Hunting Pack", original_set: "SCG" },
  { name: "Hydra's Growth", original_set: "THB" },
  { name: "Ignoble Hierarch", original_set: "MH2" },
  { name: "Incremental Growth", original_set: "LRW" },
  { name: "Indrik Stomphowler", original_set: "DIS" },
  { name: "Invigorate", original_set: "MMQ" },
  { name: "Invigorating Surge", original_set: "M21" },
  { name: "Ironhoof Ox", original_set: "P02" },
  { name: "Ironscale Hydra", original_set: "THB" },
  { name: "Iwamori of the Open Fist", original_set: "A25" },
  { name: "Jade Mage", original_set: "M12" },
  { name: "Jaspera Sentinel", original_set: "KHM" },
  { name: "Jewel Thief", original_set: "SNC" },
  { name: "Joraga Treespeaker", original_set: "ROE" },
  { name: "Jungle Lion", original_set: "POR" },
  { name: "Kappa Tech-Wrecker", original_set: "NEO" },
  { name: "Karstoderm", original_set: "DST" },
  { name: "Kavu Predator", original_set: "PLC" },
  { name: "Keen Sense", original_set: "PLC" },
  { name: "Kenrith's Transformation", original_set: "AFR" },
  { name: "Khalni Garden", original_set: "DDR" },
  { name: "Kraul Harpooner", original_set: "GRN" },
  { name: "Krosan Vorine", original_set: "LGN" },
  { name: "Land Grant", original_set: "MMQ" },
  { name: "Leatherback Baloth", original_set: "WWK" },
  { name: "Llanowar Visionary", original_set: "M21" },
  { name: "Masked Admirers", original_set: "MMA" },
  { name: "Masked Vandal", original_set: "KHM" },
  { name: "Massive Might", original_set: "VOW" },
  { name: "Master's Rebuke", original_set: "NEO" },
  { name: "Might of Old Krosa", original_set: "TSP" },
  { name: "Mobilize", original_set: "POR" },
  { name: "Moment's Peace", original_set: "TD0" },
  { name: "Monstrous Growth", original_set: "POR" },
  { name: "Muscle Burst", original_set: "ODY" },
  { name: "Muscle Sliver", original_set: "TMP" },
  { name: "Mutagenic Growth", original_set: "NPH" },
  { name: "Mwonvuli Acid-Moss", original_set: "TSP" },
  { name: "Nantuko Elder", original_set: "ODY" },
  { name: "Nantuko Vigilante", original_set: "LGN" },
  { name: "Nature's Way", original_set: "KLD" },
  { name: "Night Soil", original_set: "C13" },
  { name: "Nissa's Judgment", original_set: "DDU" },
  { name: "Noble Hierarch", original_set: "MM2" },
  { name: "Noose Constrictor", original_set: "EMN" },
  { name: "Norwood Archers", original_set: "P02" },
  { name: "Nullhide Ferox", original_set: "GRN" },
  { name: "Nylea's Presence", original_set: "THS" },
  { name: "Oakhame Adversary", original_set: "ELD" },
  { name: "Oath of Nissa", original_set: "OGW" },
  { name: "One with Nature", original_set: "SCG" },
  { name: "Orochi Eggwatcher", original_set: "CHK" },
  { name: "Outmuscle", original_set: "ELD" },
  { name: "Overgrowth", original_set: "9ED" },
  { name: "Overwhelming Encounter", original_set: "CLB" },
  { name: "Patagia Viper", original_set: "DIS" },
  { name: "Path of Discovery", original_set: "RIX" },
  { name: "Penumbra Kavu", original_set: "APC" },
  { name: "Penumbra Wurm", original_set: "UMA" },
  { name: "Phantom Tiger", original_set: "JUD" },
  { name: "Plated Crusher", original_set: "BFZ" },
  { name: "Pollenbright Druid", original_set: "WAR" },
  { name: "Predator's Howl", original_set: "CNS" },
  { name: "Predator's Strike", original_set: "MRD" },
  { name: "Presence of Gond", original_set: "SHM" },
  { name: "Primal Growth", original_set: "PLS" },
  { name: "Primal Rage", original_set: "STH" },
  { name: "Prizefight", original_set: "SNC" },
  { name: "Prosperous Innkeeper", original_set: "AFR" },
  { name: "Questing Beast", original_set: "ELD" },
  { name: "Quirion Dryad", original_set: "M21" },
  { name: "Quirion Elves", original_set: "MIR" },
  { name: "Quirion Ranger", original_set: "VIS" },
  { name: "Ram Through", original_set: "IKO" },
  { name: "Rampant Growth", original_set: "MIR" },
  { name: "Reclamation Sage", original_set: "2XM" },
  { name: "Recross the Paths", original_set: "MOR" },
  { name: "Restock", original_set: "M15" },
  { name: "Return to Nature", original_set: "ELD" },
  { name: "Rise of the Ants", original_set: "MID" },
  { name: "River Bear", original_set: "P02" },
  { name: "Saber Ants", original_set: "MMQ" },
  { name: "Salvage", original_set: "P02" },
  { name: "Sarulf's Packmate", original_set: "KHM" },
  { name: "Savage Conception", original_set: "EVE" },
  { name: "Scale Up", original_set: "MH1" },
  { name: "Scragnoth", original_set: "TMP" },
  { name: "Scurry Oak", original_set: "MH2" },
  { name: "Season of Growth", original_set: "M20" },
  { name: "Seedguide Ash", original_set: "LRW" },
  { name: "Seton's Scout", original_set: "TOR" },
  { name: "Shared Summons", original_set: "M20" },
  { name: "Sheltering Word", original_set: "AVR" },
  { name: "Silverglade Elemental", original_set: "MMQ" },
  { name: "Silverglade Pathfinder", original_set: "MMQ" },
  { name: "Skullmulcher", original_set: "2XM" },
  { name: "Skyshroud Claim", original_set: "NEM" },
  { name: "Skyshroud Elite", original_set: "EXO" },
  { name: "Skysnare Spider", original_set: "ORI" },
  { name: "Snake Pit", original_set: "MMQ" },
  { name: "Song of Freyalise", original_set: "DAR" },
  { name: "Spidersilk Armor", original_set: "MMQ" },
  { name: "Spike Colony", original_set: "STH" },
  { name: "Spore Swarm", original_set: "DAR" },
  { name: "Sporemound", original_set: "M14" },
  { name: "Squirrel Nest", original_set: "ODY" },
  { name: "Stand Together", original_set: "DST" },
  { name: "Stingerfling Spider", original_set: "M12" },
  { name: "Stinging Shot", original_set: "AKH" },
  { name: "Storm the Seedcore", original_set: "MOM" },
  { name: "Strangleroot Geist", original_set: "DKA" },
  { name: "Streetwise Negotiator", original_set: "MOM" },
  { name: "Struggle for Skemfar", original_set: "KHM" },
  { name: "Sudden Spinnerets", original_set: "IKO" },
  { name: "Summit Apes", original_set: "WWK" },
  { name: "Symbiosis", original_set: "USG" },
  { name: "Symbiotic Beast", original_set: "ONS" },
  { name: "Tail Swipe", original_set: "DMU" },
  { name: "Tangle", original_set: "INV" },
  { name: "Tear Asunder", original_set: "DMU" },
  { name: "Temur Sabertooth", original_set: "FRF" },
  { name: "Thorn Mammoth", original_set: "ELD" },
  { name: "Thundering Spineback", original_set: "XLN" },
  { name: "Timberland Ancient", original_set: "MOM" },
  { name: "Tireless Provisioner", original_set: "MH2" },
  { name: "Titanoth Rex", original_set: "IKO" },
  { name: "Tower Above", original_set: "SHM" },
  { name: "Travel Preparations", original_set: "ISD" },
  { name: "Treetop Village", original_set: "ULG" },
  { name: "Trollbred Guardian", original_set: "RNA" },
  { name: "Trollhide", original_set: "M12" },
  { name: "Trumpeting Herd", original_set: "MH1" },
  { name: "Twin-Silk Spider", original_set: "MH1" },
  { name: "Tyvar's Stand", original_set: "ONE" },
  { name: "Utopia Sprawl", original_set: "DIS" },
  { name: "Utopia Vow", original_set: "PLC" },
  { name: "Vastwood Surge", original_set: "ZNR" },
  { name: "Venomspout Brackus", original_set: "ONS" },
  { name: "Vine Mare", original_set: "M19" },
  { name: "Vines of Vastwood", original_set: "ZEN" },
  { name: "Viridian Shaman", original_set: "MRD" },
  { name: "Vivien's Grizzly", original_set: "WAR" },
  { name: "Vorstclaw", original_set: "M20" },
  { name: "Wall of Blossoms", original_set: "STH" },
  { name: "Wall of Mulch", original_set: "ONS" },
  { name: "Wall of Roots", original_set: "SNC" },
  { name: "Warbriar Blessing", original_set: "THB" },
  { name: "Wasteland Viper", original_set: "GK2" },
  { name: "Werebear", original_set: "ODY" },
  { name: "Whip Silk", original_set: "INV" },
  { name: "Wickerbough Elder", original_set: "EVE" },
  { name: "Wild Hunger", original_set: "DKA" },
  { name: "Wilt", original_set: "IKO" },
  { name: "Winding Way", original_set: "MH1" },
  { name: "Wirewood Channeler", original_set: "LGN" },
  { name: "Wirewood Guardian", original_set: "SCG" },
  { name: "Wood Elves", original_set: "EXO" },
  { name: "Woodland Changeling", original_set: "LRW" },
  { name: "Woodland Mystic", original_set: "M20" },
  { name: "Wrap in Vigor", original_set: "FUT" },
  { name: "Yavimaya Granger", original_set: "ULG" },
  { name: "Young Wolf", original_set: "DKA" },

  // ── Multicolor (89) ────────────────────────────────
  { name: "Aesi, Tyrant of Gyre Strait", original_set: "CMR" },
  { name: "Ajani, the Greathearted", original_set: "WAR" },
  { name: "Alela, Artful Provocateur", original_set: "ELD" },
  { name: "Ancient Excavation", original_set: "PZ2" },
  { name: "Ancient Lumberknot", original_set: "VOW" },
  { name: "Angel of Despair", original_set: "UMA" },
  { name: "Angelic Shield", original_set: "INV" },
  { name: "Arcades, the Strategist", original_set: "M19" },
  { name: "Ayli, Eternal Pilgrim", original_set: "OGW" },
  { name: "Backlash", original_set: "INV" },
  { name: "Batwing Brume", original_set: "EVE" },
  { name: "Bloodtithe Harvester", original_set: "VOW" },
  { name: "Boggart Ram-Gang", original_set: "SHM" },
  { name: "Burning-Tree Emissary", original_set: "GK2" },
  { name: "Cavern Harpy", original_set: "PLS" },
  { name: "Chainer, Nightmare Adept", original_set: "MH2" },
  { name: "Conclave Mentor", original_set: "M21" },
  { name: "Consuming Aberration", original_set: "GK1" },
  { name: "Countersquall", original_set: "DDH" },
  { name: "Crystalline Sliver", original_set: "STH" },
  { name: "Dimir Infiltrator", original_set: "PCA" },
  { name: "Dragonlair Spider", original_set: "PCA" },
  { name: "Dromoka's Command", original_set: "DTK" },
  { name: "Duergar Hedge-Mage", original_set: "EVE" },
  { name: "Edgewalker", original_set: "SCG" },
  { name: "Elmar, Ulvenwald Informant", original_set: "SLX" },
  { name: "Elsha of the Infinite", original_set: "2X2" },
  { name: "Expansion // Explosion", original_set: "GRN" },
  { name: "Fracture", original_set: "STX" },
  { name: "Frenetic Sliver", original_set: "PLC" },
  { name: "Gaddock Teeg", original_set: "UMA" },
  { name: "Garth One-Eye", original_set: "MH2" },
  { name: "Ghired, Conclave Exile", original_set: "C19" },
  { name: "Give // Take", original_set: "DGM" },
  { name: "Golgari Charm", original_set: "GK1" },
  { name: "Grisly Salvage", original_set: "GK1" },
  { name: "Grist, the Hunger Tide", original_set: "MH2" },
  { name: "Grizzled Leotau", original_set: "ARB" },
  { name: "Gruul War Chant", original_set: "DGM" },
  { name: "Ikra Shidiqi, the Usurper", original_set: "CM2" },
  { name: "Inkfathom Infiltrator", original_set: "SHM" },
  { name: "Inside Out", original_set: "EVE" },
  { name: "Iroas, God of Victory", original_set: "C16" },
  { name: "Jhoira of the Ghitu", original_set: "DDS" },
  { name: "Junkyard Genius", original_set: "BRO" },
  { name: "Kiora, Behemoth Beckoner", original_set: "WAR" },
  { name: "Klauth, Unrivaled Ancient", original_set: "AFR" },
  { name: "Klothys, God of Destiny", original_set: "THB" },
  { name: "Kwain, Itinerant Meddler", original_set: "CMR" },
  { name: "Leovold, Emissary of Trest", original_set: "CN2" },
  { name: "Liesa, Shroud of Dusk", original_set: "CMR" },
  { name: "Lightning Skelemental", original_set: "MH1" },
  { name: "Mantis Rider", original_set: "KTK" },
  { name: "Mayhem Devil", original_set: "WAR" },
  { name: "Mazirek, Kraul Death Priest", original_set: "2XM" },
  { name: "Mercy Killing", original_set: "SHM" },
  { name: "Momir Vig, Simic Visionary", original_set: "GK2" },
  { name: "Murderous Redcap", original_set: "SHM" },
  { name: "Pernicious Deed", original_set: "A25" },
  { name: "Poison-Tip Archer", original_set: "KHM" },
  { name: "Prosper, Tome-Bound", original_set: "AFR" },
  { name: "Prossh, Skyraider of Kher", original_set: "A25" },
  { name: "Puresight Merrow", original_set: "SHM" },
  { name: "Qasali Ambusher", original_set: "ALA" },
  { name: "Quicksilver Dagger", original_set: "APC" },
  { name: "Ral, Storm Conduit", original_set: "WAR" },
  { name: "Razorfin Hunter", original_set: "APC" },
  { name: "Reconstruct History", original_set: "STX" },
  { name: "Rootha, Mercurial Artist", original_set: "STX" },
  { name: "Shield of the Oversoul", original_set: "SHM" },
  { name: "Showdown of the Skalds", original_set: "KHM" },
  { name: "Silumgar, the Drifting Death", original_set: "FRF" },
  { name: "Skyknight Vanguard", original_set: "M20" },
  { name: "Slippery Bogle", original_set: "EVE" },
  { name: "Sorin, Solemn Visitor", original_set: "KTK" },
  { name: "Spitemare", original_set: "EVE" },
  { name: "Squee's Embrace", original_set: "APC" },
  { name: "Stangg", original_set: "A25" },
  { name: "Steel of the Godhead", original_set: "SHM" },
  { name: "Svella, Ice Shaper", original_set: "KHM" },
  { name: "Swans of Bryn Argoll", original_set: "MM2" },
  { name: "Temporal Spring", original_set: "APC" },
  { name: "Thantis, the Warweaver", original_set: "C18" },
  { name: "Trostani, Selesnya's Voice", original_set: "GK1" },
  { name: "Trygon Predator", original_set: "GK2" },
  { name: "Unmake", original_set: "EVE" },
  { name: "Vindicate", original_set: "A25" },
  { name: "Wall of Denial", original_set: "ARB" },
  { name: "Witherbloom Apprentice", original_set: "STX" },

  // ── Colorless/Artifacts (48) ───────────────────────
  { name: "Agent of Acquisitions", original_set: "CNS" },
  { name: "Angel's Trumpet", original_set: "ULG" },
  { name: "Belbe's Armor", original_set: "NEM" },
  { name: "Bonder's Ornament", original_set: "IKO" },
  { name: "Chromatic Sphere", original_set: "INV" },
  { name: "Circuit Mender", original_set: "NEO" },
  { name: "Coalition Relic", original_set: "A25" },
  { name: "Cogwork Librarian", original_set: "CNS" },
  { name: "Containment Construct", original_set: "NEO" },
  { name: "Crackdown Construct", original_set: "AER" },
  { name: "Crystalline Crawler", original_set: "CM2" },
  { name: "Darksteel Ingot", original_set: "DST" },
  { name: "Decanter of Endless Water", original_set: "CLB" },
  { name: "Dingus Staff", original_set: "WTH" },
  { name: "Empowered Autogenerator", original_set: "C19" },
  { name: "Firemind Vessel", original_set: "WAR" },
  { name: "God-Pharaoh's Gift", original_set: "HOU" },
  { name: "God-Pharaoh's Statue", original_set: "WAR" },
  { name: "Goldvein Pick", original_set: "KHM" },
  { name: "Gorgon Flail", original_set: "M10" },
  { name: "Hangarback Walker", original_set: "ORI" },
  { name: "Heartstone", original_set: "H09" },
  { name: "Heraldic Banner", original_set: "ELD" },
  { name: "Hymn of the Wilds", original_set: "CN2" },
  { name: "Letter of Acceptance", original_set: "STX" },
  { name: "Ornithopter of Paradise", original_set: "MH2" },
  { name: "Paradise Mantle", original_set: "MMA" },
  { name: "Patchwork Automaton", original_set: "NEO" },
  { name: "Patriar's Seal", original_set: "CLB" },
  { name: "Pearl Shard", original_set: "MRD" },
  { name: "Phyrexian Walker", original_set: "VIS" },
  { name: "Planar Atlas", original_set: "J22" },
  { name: "Power Conduit", original_set: "MRD" },
  { name: "Prismatic Lens", original_set: "UMA" },
  { name: "Puppet Strings", original_set: "TMP" },
  { name: "Relic of Legends", original_set: "DMU" },
  { name: "Replicating Ring", original_set: "MOM" },
  { name: "Scuttlemutt", original_set: "SHM" },
  { name: "Serrated Biskelion", original_set: "WTH" },
  { name: "Shuko", original_set: "BOK" },
  { name: "Signal Pest", original_set: "MBS" },
  { name: "Skittering Surveyor", original_set: "DAR" },
  { name: "Smuggler's Copter", original_set: "KLD" },
  { name: "Spawning Pit", original_set: "TD2" },
  { name: "Star Compass", original_set: "PLS" },
  { name: "Viridian Claw", original_set: "MBS" },
  { name: "Viridian Longbow", original_set: "AFR" },
  { name: "Worn Powerstone", original_set: "USG" },

  // ── Lands (30) ─────────────────────────────────────
  { name: "Archway Commons", original_set: "STX" },
  { name: "Cryptic Spires", original_set: "2X2" },
  { name: "Crystal Grotto", original_set: "DMU" },
  { name: "Crystal Vein", original_set: "MIR" },
  { name: "Desert", original_set: "AFR" },
  { name: "Elfhame Palace", original_set: "8ED" },
  { name: "Frost Marsh", original_set: "CSP" },
  { name: "Gemstone Mine", original_set: "WTH" },
  { name: "Ghost Town", original_set: "TMP" },
  { name: "Guildless Commons", original_set: "CMR" },
  { name: "Izzet Boilerworks", original_set: "GK1" },
  { name: "Mountain Valley", original_set: "MIR" },
  { name: "Mystic Monastery", original_set: "KTK" },
  { name: "Nomad Outpost", original_set: "DMU" },
  { name: "Opulent Palace", original_set: "KTK" },
  { name: "Painted Bluffs", original_set: "AKH" },
  { name: "Quicksand", original_set: "VIS" },
  { name: "Rimewood Falls", original_set: "KHM" },
  { name: "Rustvale Bridge", original_set: "MH2" },
  { name: "Savage Lands", original_set: "ALA" },
  { name: "Seaside Citadel", original_set: "ALA" },
  { name: "Shimmerdrift Vale", original_set: "KHM" },
  { name: "Skybridge Towers", original_set: "SNC" },
  { name: "Sunlit Marsh", original_set: "DMU" },
  { name: "Survivors' Encampment", original_set: "HOU" },
  { name: "Tainted Wood", original_set: "TOR" },
  { name: "Terrain Generator", original_set: "NEM" },
  { name: "Terramorphic Expanse", original_set: "M21" },
  { name: "Unstable Frontier", original_set: "CON" },
  { name: "Urborg Volcano", original_set: "INV" },
];
